### ISSUE TITLE
对于复杂、计算耗时较长的目标函数，请问遗传算法是否可以分配多个个体到多核上并行计算？

### ISSUE THREAD

**Issue by meihaojie** [guofei9987/scikit-opt#101]

**Comment by guofei9987** [comment]
稳定版本已支持：矢量化计算。

开发版本已支持：
- 并行计算
- 缓存

参考：https://github.com/guofei9987/scikit-opt/issues/94，将于下个版本优化后发布

**Comment by guofei9987** [comment]
0.6.2 版本已经支持以下加速：
- 并行化计算
- 矢量化计算
- 缓存化计算

中文文档： https://scikit-opt.github.io/scikit-opt/#/zh/speed_up  
英文文档：https://scikit-opt.github.io/scikit-opt/#/en/speed_up
