### ISSUE TITLE
目前的并行化似乎只是多线程，能否采用多进程以充分利用多核？

### ISSUE THREAD

**Issue by meihaojie** [guofei9987/scikit-opt#107]
如果优化函数是计算密集型的，经过测试，目前的并行化并不能节省时间。

**Comment by guofei9987** [comment]
现在用的是多进程。

刚刚测试了大计算量整除和大计算量对数任务。并行的耗时基本上减半。  
CPU是旧的 Core i-5 4300U  
监控CPU消耗发现4个核心都接近50%使用。  
没到100%应该是因为没用多线程？

**Comment by guofei9987** [comment]
我用pid打印，发现确实没有开启多个pid，我再研究一下

**Comment by guofei9987** [comment]
开发版已经支持多进程：

```
def obj_func3_2(p):
    time.sleep(0.1)  # say that this function is very complicated and cost 0.1 seconds to run
    x1, x2 = p
    x = np.square(x1) + np.square(x2)
    return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)


set_run_mode(obj_func3_2, 'multiprocess')
ga3_2 = GA(func=obj_func3_2, n_dim=2, size_pop=6, max_iter=5, lb=[-1, -1], ub=[1, 1], precision=1e-7)
start_time = datetime.datetime.now()
best_x, best_y = ga3_2.run()
print('multiprocess mode, time costs: ', (datetime.datetime.now() - start_time).total_seconds())
```

但不支持windows

欢迎反馈测试结果

**Comment by guofei9987** [comment]
本次测试结果：

(CPU costs)
>common mode, time costs:  15.766918
vector mode, time costs:  1.927389
parallel mode, time costs:  9.703426
multiprocess mode, time costs:  3.477673



(IO costs)
>common mode, time costs:  5.245224
vector mode, time costs:  0.627793
parallel mode, time costs:  0.629251
multiprocess mode, time costs:  0.625127


整体感觉还可以，稍后把 test cases 更新到 example/example_function_modes.py

**Comment by meihaojie** [comment]
在执行example_function_modes.py时，是可以看到多个pid的，多进程应该是成功的。但执行代码：

 import numpy as np
 import time
 import datetime
 from sko.GA import GA
 from sko.tools import set_run_mode

 class YourClass:
     def __init__(self, param=1):
         self.param = param

     def obj_func1(self, p):
         time.sleep(0.1)  # say that this function is very complicated and cost 0.1 seconds to run
         x1, x2 = p
         x = np.square(x1) + np.square(x2)
         return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)

     def obj_func2(self, p):
         time.sleep(0.1)  # say that this function is very complicated and cost 1 seconds to run
         x1, x2 = p[:, 0], p[:, 1]
         x = np.square(x1) + np.square(x2)
         return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)

     def obj_func3_1(self, p):
         time.sleep(0.1)  # say that this function is very complicated and cost 0.1 seconds to run
         x1, x2 = p
         x = np.square(x1) + np.square(x2)
         return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)

     def obj_func3_2(self, p):
         time.sleep(0.1)  # say that this function is very complicated and cost 0.1 seconds to run
         x1, x2 = p
         x = np.square(x1) + np.square(x2)
         return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)

     def obj_func4(self,p):
         time.sleep(0.1)  # say that this function is very complicated and cost 0.1 seconds to run
         x1, x2 = p
         x = np.square(x1) + np.square(x2)
         return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)

 your_class = YourClass()

 set_run_mode(your_class.obj_func2, 'vectorization')
 set_run_mode(your_class.obj_func3_1, 'parallel')
 set_run_mode(your_class.obj_func3_2, 'multiprocess')
 set_run_mode(your_class.obj_func4, 'cached')

 ga1 = GA(func=your_class.obj_func1, n_dim=2, size_pop=10, max_iter=5, lb=[-1, -1], ub=[1, 1], precision=1e-7)
 ga2 = GA(func=your_class.obj_func2, n_dim=2, size_pop=10, max_iter=5, lb=[-1, -1], ub=[1, 1], precision=1e-7)
 ga3_1 = GA(func=your_class.obj_func3_1, n_dim=2, size_pop=10, max_iter=5, lb=[-1, -1], ub=[1, 1], precision=1e-7)
 ga3_2 = GA(func=your_class.obj_func3_2, n_dim=2, size_pop=10, max_iter=5, lb=[-1, -1], ub=[1, 1], precision=1e-7)
 ga4 = GA(func=your_class.obj_func4, n_dim=2, size_pop=10, max_iter=5, lb=[-1, -1], ub=[1, 1], precision=1e-7)

 start_time = datetime.datetime.now()
 best_x, best_y = ga1.run()
 print('common mode, time costs: ', (datetime.datetime.now() - start_time).total_seconds())
start_time = datetime.datetime.now()
 best_x, best_y = ga2.run()
 print('vectorization mode, time costs: ', (datetime.datetime.now() - start_time).total_seconds())

 start_time = datetime.datetime.now()
 best_x, best_y = ga3_1.run()
 print('parallel mode, time costs: ', (datetime.datetime.now() - start_time).total_seconds())

 start_time = datetime.datetime.now()
 best_x, best_y = ga3_2.run()
 print('multiprocess mode, time costs: ', (datetime.datetime.now() - start_time).total_seconds())

 start_time = datetime.datetime.now()
 best_x, best_y = ga4.run()
 print('cache mode, time costs: ', (datetime.datetime.now() - start_time).total_seconds())

发现并没有多个pid，且运行时间没有缩短。
运行时间：
common mode, time costs:  5.120296
vectorization mode, time costs:  0.607186
parallel mode, time costs:  1.113097
multiprocess mode, time costs:  5.122365
cache mode, time costs:  4.018713
测试系统信息：Ubuntu 16.04.5 LTS，8  Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz

**Comment by guofei9987** [comment]
macOS 跑你的代码 
>common mode, time costs:  5.276445
vectorization mode, time costs:  0.630478
parallel mode, time costs:  1.142528
multiprocess mode, time costs:  1.126135
cache mode, time costs:  4.011704

docker 开4核结果：
>common mode, time costs:  5.214862
vectorization mode, time costs:  0.612851
parallel mode, time costs:  1.646428
multiprocess mode, time costs:  1.649229
cache mode, time costs:  2.667592


突然想起来，你的测试用 scikit-opt 是不是之前发布的正式版？应当先下载最新的代码库，然后用 `python setup.py install` 安装开发版

**Comment by meihaojie** [comment]
感谢，下载最新的代码后，问题已解决。

**Comment by guofei9987** [comment]
嗯，好。我整理一下代码，过段时间发布下一个版本。
