### ISSUE TITLE
如何在第一层搜索里面再嵌套一层局部搜索？

### ISSUE THREAD

**Issue by cliff0149** [guofei9987/scikit-opt#108]
我外层搜索的目标函数是这样写的，我需要根据ant.step4（）得到的结果（存储在ant的属性当中）再进行一次搜索，请问这个应该如何去写呢？
def obj_func(x):
    jobs=read_data(Const.filename)#读取作业信息
    ant = Antibody(jobs, x)#创建抗体实例
    ant.step1()#按照随机键进行分组
    ant.step2()#根据分组计算发车时间
    ant.step3()
    ant.step4()
    #ant_a=Antibody_a(ant)
    ant.step5()
    ant.cal_obj()#计算该抗体目标函数值
    return ant.obj

**Comment by guofei9987** [comment]
没太看懂，把里面那一层搜索和外层搜索放一起？两套自变量合起来作为一个目标函数？

**Comment by cliff0149** [comment]
对，我的目标函数是两套自变量的目标函数的加权之和。我的问题是这样的：我有60个物料要分批配送，我用x给它们赋值，按x的大小作为他们的配送顺序，然后经过解码得到第一种小车的出行次数；然后会出现一些无法配送的物料，我再对他们进行编码，得到一组配送顺序，再设计类似的解码过程，搜索求出第二种小车的最少出行次数。最后以这两种小车出行次数的加权和为目标函数。把这两种自变量的码编在一起是可以的，但是可能会增加不必要的搜索次数。我在添加局部搜索这一步的时候感觉遇到的主要困难是不能把obj_func（见下图）添加到类当中去，让它可以获得该类在实例化过程中产生的无法配送的物料集合，因为它只有x一个参数可以赋。（可能有其他方便的方法我没有找到）
如果还有我没有表述清楚的地方，您可以指出来我再说明。非常感谢！








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guofei9987/scikit-opt] 如何在第一层搜索里面再嵌套一层局部搜索？ (#108)





 
没太看懂，把里面那一层搜索和外层搜索放一起？两套自变量合起来作为一个目标函数？

**Comment by cliff0149** [comment]
> 没太看懂，把里面那一层搜索和外层搜索放一起？两套自变量合起来作为一个目标函数？

我发现在更新了0.6.2版本之后，已经可以使用类方法来实现嵌套搜索，再次感谢

**Comment by a0960909060** [comment]
從我的iPhone 傳送

**Comment by a0960909060** [comment]
從我的iPhone 傳送

**Comment by a0960909060** [comment]
從我的iPhone 傳送

**Comment by a0960909060** [comment]
從我的iPhone 傳送
