### ISSUE TITLE
请问为什么遗传算法验算到最后会不断地在两个极端跳跃

### ISSUE THREAD

**Issue by qiujunhan** [guofei9987/scikit-opt#109]
![QQ截图20210328105811](https://user-images.githubusercontent.com/38062062/112741048-ac262b80-8fb4-11eb-89e5-f5221d5e52c4.png)
![QQ截图20210328105727](https://user-images.githubusercontent.com/38062062/112741056-b516fd00-8fb4-11eb-8c7c-9262b7b9ff33.png)
![QQ截图20210328105703](https://user-images.githubusercontent.com/38062062/112741059-bba57480-8fb4-11eb-9dad-24d13ee82c3c.png)
![QQ截图20210328105652](https://user-images.githubusercontent.com/38062062/112741062-bd6f3800-8fb4-11eb-9941-af40689bb0f0.png)
如图所示，计算到后面P给出的值都在这两组数据不断重复

**Comment by qiujunhan** [comment]
补充说明，如图所示，突变率不高，种群数量也不低

**Comment by guofei9987** [comment]
目标函数给我一下

**Comment by qiujunhan** [comment]
def cal_score(self,p):
        print(p)
        # week_or_month, frequency_week, start_week, start_month_day, target_profit, sell_share, dividend_method = p
        target_profit, sell_share, dividend_method = p
        week_or_month = 1
        frequency_week = 1
        start_week = 1
        start_month_day = 1
        player = Player("bot", self.money, self.funds_objects)
        fund_ids = self.funds_objects.keys()
        for fund_id in fund_ids:

            player.simulation(fund_id, self.input_start_time, self.input_end_time, week_or_month, frequency_week, target_profit,
                              sell_share, start_week, start_month_day)

        player.caculate_score(target_profit)
        score = player.score
        self.average_yield = player.average_yield
        print("score", score)
        print("average_yield", self.average_yield)
        return -score
        
目标函数是这样的，但是我是调用了一个类里面的函数，这个函数根据给定的时间范围，投资策略模拟了一次基金投资，投资的收益率越高，得分就越高

**Comment by guofei9987** [comment]
> ```
> def cal_score(self,p):
>     print(p)
>     # week_or_month, frequency_week, start_week, start_month_day, target_profit, sell_share, dividend_method = p
>     target_profit, sell_share, dividend_method = p
>     week_or_month = 1
>     frequency_week = 1
>     start_week = 1
>     start_month_day = 1
>     player = Player("bot", self.money, self.funds_objects)
>     fund_ids = self.funds_objects.keys()
>     for fund_id in fund_ids:
> 
>         player.simulation(fund_id, self.input_start_time, self.input_end_time, week_or_month, frequency_week, target_profit,
>                           sell_share, start_week, start_month_day)
> 
>     player.caculate_score(target_profit)
>     score = player.score
>     self.average_yield = player.average_yield
>     print("score", score)
>     print("average_yield", self.average_yield)
>     return -score
> ```
> 
> 目标函数是这样的，但是我是调用了一个类里面的函数，这个函数根据给定的时间范围，投资策略模拟了一次基金投资，投资的收益率越高，得分就越高

这个函数看起来不能单独运行

**Comment by qiujunhan** [comment]
> > ```
> > def cal_score(self,p):
> >     print(p)
> >     # week_or_month, frequency_week, start_week, start_month_day, target_profit, sell_share, dividend_method = p
> >     target_profit, sell_share, dividend_method = p
> >     week_or_month = 1
> >     frequency_week = 1
> >     start_week = 1
> >     start_month_day = 1
> >     player = Player("bot", self.money, self.funds_objects)
> >     fund_ids = self.funds_objects.keys()
> >     for fund_id in fund_ids:
> > 
> >         player.simulation(fund_id, self.input_start_time, self.input_end_time, week_or_month, frequency_week, target_profit,
> >                           sell_share, start_week, start_month_day)
> > 
> >     player.caculate_score(target_profit)
> >     score = player.score
> >     self.average_yield = player.average_yield
> >     print("score", score)
> >     print("average_yield", self.average_yield)
> >     return -score
> > ```
> > 
> > 
> > 目标函数是这样的，但是我是调用了一个类里面的函数，这个函数根据给定的时间范围，投资策略模拟了一次基金投资，投资的收益率越高，得分就越高
> 
> 这个函数看起来不能单独运行

    def demo_cal_score(p):

        return start.cal_score(p)
这是真目标函数，做了一层封装

**Comment by qiujunhan** [comment]
![微信截图_20210330004930](https://user-images.githubusercontent.com/38062062/112871447-daf5ec00-90f1-11eb-8e00-8ecc62303729.png)
![微信截图_20210330003949](https://user-images.githubusercontent.com/38062062/112871495-e47f5400-90f1-11eb-8ccd-7b08971dafd6.png)
似乎种群数量越多，就容易陷入两头极端的情况,例如150、300个。话说大佬不打算做一个保留每一代最优的n个个体的方法吗。这样不至于好的个体被刷掉

**Comment by guofei9987** [comment]
我用其它函数测了一下，也复现了这个问题。但这应该不是bug，是突变导致少数个体偶尔跳跃，是正常现象。可以设置 `prob_mut =0 ` 试试效果。

一个基因 [1,0,0] 突变到 [0,0,0] ，对应的值会从最大变到最小。  

一个变量对应的基因，会有1个变化的影响最大，其它的0.5倍依次降低。  
所以优化到最后时，某个基因突变引起跳跃较大，其它基因突变几乎不影响跳跃。假如染色体长度20，精度设为1e-7，可能18个基因突变会让值在 1e-2 之内变化，画到图上可以忽略不计，另外2个突变就看起来像是在跳跃。

**Comment by guofei9987** [comment]
另外，我没测过其它遗传算法工具，如果其它的不是这样的，可以告诉我。
