### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (400,1) (20,30) (20,30)

### ISSUE THREAD

**Issue by cliff0149** [guofei9987/scikit-opt#111]
我在算法内部又添加一层搜索之后就出现了这个报错，但是报错的是外层的搜索而不是内层的。问题是在selection这里，似乎是说对于np.where函数，条件矩阵和后面的矩阵维数不同。但是我将条件矩阵打印出来发现它就是一个（20，1）的矩阵，不知道为什么程序认定它为（400，1）
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]]
迭代次数 0 最优值 [27.6]
Traceback (most recent call last):
  File "D:/Desktop/半集成式VRPSDP/代码/main.py", line 121, in <module>
    best_x, best_y = de.run()
  File "D:\841370\anaconda\lib\site-packages\sko\DE.py", line 86, in run
    self.selection()
  File "D:\841370\anaconda\lib\site-packages\sko\DE.py", line 76, in selection
    self.X = np.where((f_X < f_U).reshape(-1, 1), X, U)
  File "<__array_function__ internals>", line 5, in where
ValueError: operands could not be broadcast together with shapes (400,1) (20,30) (20,30) 

此外还有一个报错VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array([func_cached(tuple(x)) for x in X])没有找到原因。

**Comment by cliff0149** [comment]
并且不是每一次迭代都会报这个错，有时候会迭代七八十次之后才报这个错。如果将这个内层搜索移除则不会报任何错。

**Comment by guofei9987** [comment]
第一个报错应该是输入值不对，输入值只有一个的时候也要传入 tuple

第二个报错可能是打开了 cache 模式，但 cache 模式不支持 np.array 作为输入

**Comment by cliff0149** [comment]
> 第一个报错应该是输入值不对，输入值只有一个的时候也要传入 tuple
> 
> 第二个报错可能是打开了 cache 模式，但 cache 模式不支持 np.array 作为输入

但是我的输入值并不只有一个，我发现当把np.where((f_X < f_U).reshape(-1, 1)改成 f_X.reshape(-1, 1) < f_U.reshape(-1, 1)的时候就不会报错了，不知道为什么

**Comment by a0960909060** [comment]
> > 第一个报错应该是输入值不对，输入值只有一个的时候也要传入 tuple
> > 第二个报错可能是打开了 cache 模式，但 cache 模式不支持 np.array 作为输入
> 
> 但是我的输入值并不只有一个，我发现当把np.where((f_X < f_U).reshape(-1, 1)改成 f_X.reshape(-1, 1) < f_U.reshape(-1, 1)的时候就不会报错了，不知道为什么
