### ISSUE TITLE
Windows为什么不支持multiprocessing？

### ISSUE THREAD

**Issue by Jackwangnao** [guofei9987/scikit-opt#116]
运行“目标函数加速”中的例子（/examples/example_function_modes.py）时，出现UserWarning：multiprocessing not support in windows, turning to multithreading warnings.warn('multiprocessing not support in windows, turning to multithreading'。

查看源码发现：
if mode == 'multiprocessing' and sys.platform == 'win32':
         warnings.warn('multiprocessing not support in windows, turning to multithreading')
         mode = 'multithreading'

可是 windows 也可以使用 `multiprocessing` 库，并且也可以使用 `Pool`，请问为什么这里不支持呢？

**Comment by guofei9987** [comment]
多进程在windows下，如果不加 `if __name__ == '__main__':`，会进入无限递归然后报错。

https://www.guofei.site/2021/02/13/python_speedup.html

如果有好的解决方法也可以发一下。
