### ISSUE TITLE
为什么约束条件没有遵守

### ISSUE THREAD

**Issue by binxiaoxiaobin** [guofei9987/scikit-opt#118]
有一个线性规划问题，变量大概几十个，然后设置了每个变量的lb 和ub，也设置了constraint_ueq，但是变量再求解过程中只满足了lb和ub没有满足constraint_ueq，这是为什么，而且constraint_ueq里基本都是x+y+z<=10 之类的

**Comment by OliverShang** [comment]
同样遇到此问题，请问有解决吗？

**Comment by willwang97** [comment]
我的constraint_eq也无效，请问解决了吗？
