### ISSUE TITLE
目标函数的格式要求太严格了

### ISSUE THREAD

**Issue by ilikega** [guofei9987/scikit-opt#12]
```
def demo_func(x):
    x1, x2, x3 = x
    return x1 ** 2 + (x2 - 0.05) ** 2 + x3 ** 2
```

很多人习惯这么用
```
def demo_func(x, y, z):
    return x + y + z
```

**Comment by guofei9987** [comment]
这确实是一个问题，实际上常用的目标函数样式有4种（或许更多）。
在设计之初想过要兼顾计算效率和多样式的兼容性，但迟迟没有找到一个完美的解决方案。参考其它库，都是进行了一些取舍，因此这个问题搁置到现在。

下一步会想办法解决这个问题，即使是不完美的解决。

ps，目前用的格式是 `scipy.optimize` 的格式，并且并没有进行运行效率上的改进。

**Comment by guofei9987** [comment]
补充，目前已知常用的4种目标函数样式
1. 目前唯一支持的
```
def demo_func(x):
    x1, x2, x3 = x
    return x1 ** 2 + (x2 - 0.05) ** 2 + x3 ** 2
```
2. 多个输入的
```
def demo_func(x,y,z):
    return x**2+y**2+z**2
```
3. 多个输入，但支持矢量化运算的
```
def demo_func(x,y,z):
    return np.square(x)+np.square(y)+np.square(z)
```
3兼容2，但2不兼容3，会导致用户的一些误解，这也是迟迟没动手支持的原因
4. 输入一个m×n矩阵，输出m×1的y值
```
def demo_func(X):
    return np.sum(np.square(X),axis=1)
```
4也是运行效率最高的，但功能受限，也容易与1混淆

**Comment by guofei9987** [comment]
更新：目前代码库已经支持前面提到的1,2,3 这三种函数格式了，将在下一个版本release
考虑到运算效率，仍然以demo的格式为最佳推荐。
至于第4种格式，尚无时间表。
