### ISSUE TITLE
How to pass extra argument to the objective function?

### ISSUE THREAD

**Issue by KCWang010** [guofei9987/scikit-opt#134]
For example, if the objective function is as follows:

def obj_func(p, arg):
	x1, x2 = p
	return return x1 + x2 + arg

where p represents the decision variable. Then how to pass the extra argument 'arg' to the parameter 'func' in the following GA code:

ga = GA(func=obj_func, n_dim=2, size_pop=50, max_iter=800, prob_mut=0.001, lb=[-1, -1], ub=[1, 1], precision=1e-7)

**Comment by guofei9987** [comment]
#57
