### ISSUE TITLE
GA auto tranfer value, make things wrong

### ISSUE THREAD

**Issue by CuiDachao** [guofei9987/scikit-opt#14]
hi， 我在使用GA函数时，函数中矩阵会自动迭代为上一次结果，我其实是不希望我定义的矩阵发生改变。传递时用了self，可能是主要原因，但不用self又无法作为定量传入。

**Comment by CuiDachao** [comment]
我只能使用tuple作为输入

**Comment by guofei9987** [comment]
@CuiDachao 我看看你的代码，好确认一下问题的描述

**Comment by guofei9987** [comment]
一个多月了，我先 close 了，有需要补充的再open
