### ISSUE TITLE
文档中中英文的入参那栏不对应

### ISSUE THREAD

**Issue by ticket-h** [guofei9987/scikit-opt#143]
中文的文档给的入参中constraint_eq和constraint_ueq分别对应线性约束和非线性约束，而英文则分别是equal constraint和unequal constraint，似乎英文的说明是正确的？实例也恰好对应了线性的等式约束和非线性的不等式约束，还是令人有些困惑的，希望校正一下，谢谢。

**Comment by guofei9987** [comment]
确实是错误，马上修复！

**Comment by guofei9987** [comment]
已修复，感谢反馈！🙏

https://github.com/guofei9987/scikit-opt/commit/659e7ed18a5675025d365b9bdf0bc18b90651644

https://scikit-opt.github.io/scikit-opt/#/zh/args
