### ISSUE TITLE
请问可以同时实现矢量化和多线程\多进程加速吗？

### ISSUE THREAD

**Issue by ticket-h** [guofei9987/scikit-opt#145]
尝试使用矢量化提升代码效率，效果显著，但是cpu占用不是很高，不知能否同时使用矢量化和多线程\多进程来提升代码效率。自己尝试时提示我set_run_mode只能传入两个参数，因此前来求问，还请不吝赐教。

**Comment by guofei9987** [comment]
不能，且没有必要。矢量化已经很快了，再开多线程/多进程，其时间成本将超过收益
