### ISSUE TITLE
粒子群算法限制上下界代码有误

### ISSUE THREAD

**Issue by Masterwater-y** [guofei9987/scikit-opt#148]
在PSO.py第135行中
`    def update_X(self):
        self.X = self.X + self.V
        self.X=np.clip(self.X, self.lb, self.ub)`
其中X为二维列表，此处可能应该修改为
self.X[0]=np.clip(self.X[0],self.lb,self.ub)
否则无法实现控制上下界

**Comment by guofei9987** [comment]
这里应该没错，这个代码的目的就是把对所有的粒子，统一卡上下界。

例如：
```
X = np.array([[1, 2, 3],
              [4, 5, 6]])

lb = np.array([2, -100, -100])
ub = np.array([3, 100, 100])
np.clip(X, lb, ub)
```

得到
>array([[2, 2, 3],
       [3, 5, 6]])
