### ISSUE TITLE
pso_ani.py

### ISSUE THREAD

**Issue by 14725836900** [guofei9987/scikit-opt#149]
运行pso_ani.py并没有报错，但是显示不出粒子运动轨迹，这是为什么呢？？

**Comment by guofei9987** [comment]
> 运行pso_ani.py并没有报错，但是显示不出粒子运动轨迹，这是为什么呢？？

与你的电脑配置有关，提供了
```
ani.save('pso.gif', writer='pillow')
```
可以把动图保存

**Comment by 14725836900** [comment]
![Snipaste_2021-09-27_21-57-36](https://user-images.githubusercontent.com/59506524/134923144-4dd64e9f-b584-4715-beea-23459783e09d.jpg)
添加了ani.save('pso.gif', writer='pillow')也不行。。。。。。。

**Comment by guofei9987** [comment]
> ![Snipaste_2021-09-27_21-57-36](https://user-images.githubusercontent.com/59506524/134923144-4dd64e9f-b584-4715-beea-23459783e09d.jpg) 添加了ani.save('pso.gif', writer='pillow')也不行。。。。。。。

试试用命令行启动 py 脚本
