### ISSUE TITLE
在使用遗传算法时报错

### ISSUE THREAD

**Issue by yuanbei9717** [guofei9987/scikit-opt#152]
> 我定义的函数是:

    def transfer(p,model,likelihood,ymin):
        x1,x2,x3,x4,x5= p
        input_array=np.array([x1,x2,x3,x4,x5])
        input_tensor=torch.from_numpy(input_array).to(torch.float32)
        input_tensor=input_tensor.view(1,-1)
        model.eval()                     
        likelihood.eval()
        mu=likelihood(model(input_tensor)).mean
        sigma=torch.sqrt(likelihood(model(input_tensor)).variance)
        Y=(ymin-mu)/sigma
        N_D=torch.distributions.normal.Normal(torch.tensor([0.0]), torch.tensor([1]))
        cdf=N_D.cdf(Y)
        pdf=torch.exp(N_D.log_prob(Y))
        result=sigma*pdf+(ymin-mu)*cdf
        result=result.detach().numpy()
        result=(-1)*result
        result=result.reshape(1,-1)
        return result
    def Expected_Improvement(p):
        x1,x2,x3,x4,x5= p
        return transfer(p,model,likelihood,ymin) 

然后在运行
`ga = GA(func=Expected_Improvement, n_dim=5, size_pop=50, max_iter=100, prob_mut=0.001, lb=[0,0,0,0,0], ub=[1,1,1,1,1], precision=1e-7)
best_x, best_y = ga.run()`

时会报错：
E:\anaconda\lib\site-packages\sko\operators\crossover.py in crossover_2point_bit(self)
     42         mask[i, n1:n2] = 1
     43     mask2 = (Chrom1 ^ Chrom2) & mask
---> 44     Chrom1 ^= mask2
     45     Chrom2 ^= mask2
     46     return self.Chrom

ValueError: non-broadcastable output operand with shape (25,1,1,120) doesn't match the broadcast shape (25,1,25,120)

相同的目标函数定义，在使用粒子群算法PSO时可以运行，说明目标函数的定义应该没问题
但是遗传算法在交叉的步骤就会报以上的错误
百思不得其解，希望您有时间时帮忙看一下，非常感谢！

**Comment by guofei9987** [comment]
我跑了一下没有报错，检查一下各个变量是否正确传进去？
