### ISSUE TITLE
GA_tsp的算例代码报错

### ISSUE THREAD

**Issue by BalwynZhang** [guofei9987/scikit-opt#16]
TypeError: __init__() missing 1 required positional argument: 'n_dim'

**Comment by guofei9987** [comment]
@BalwynZhang 感谢提醒，文档没有及时更新。
正确用法在这里 https://github.com/guofei9987/scikit-opt/blob/master/examples/demo_ga_tsp.py

我现在去更新一下文档

**Comment by BalwynZhang** [comment]
> @BalwynZhang 感谢提醒，文档没有及时更新。
> 正确用法在这里 https://github.com/guofei9987/scikit-opt/blob/master/examples/demo_ga_tsp.py
> 
> 我现在去更新一下文档
> 
> 现在文档已更新完

谢谢，会持续关注您~！

**Comment by guofei9987** [comment]
你好，感谢你提交的bug，是否允许在 *scikit-opt 1.0* 版本把你列为contributor呢？

**Comment by BalwynZhang** [comment]
可以，谢谢！



---原始邮件---
发件人: "郭飞"<notifications@github.com&gt;
发送时间: 2020年5月2日(周六) 中午12:41
收件人: "guofei9987/scikit-opt"<scikit-opt@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Bowen Zhang"<zhang-bowen@foxmail.com&gt;;
主题: Re: [guofei9987/scikit-opt] GA_tsp的算例代码报错 (#16)




 
你好，感谢你提交的bug，是否允许在 scikit-opt 1.0 版本把你列为contributor呢？
