### ISSUE TITLE
固定起点与终点的TSP

### ISSUE THREAD

**Issue by bye-byte** [guofei9987/scikit-opt#179]
#58 按照遗传算法固定起点与终点中的思路，蚁群算法是否可以在更改距离函数的情况下得到转换？
做了一点尝试，但似乎不太行。

**Comment by bye-byte** [comment]
似乎要对源码进行一些修改，即初始化时蚂蚁的初始点只能是起点，并且如果没访问的城市还有两个或者以上那么就设置终点不可访问

**Comment by guofei9987** [comment]
按照遗传算法那样改就行了，去掉环路那一个值。ACA每个路径默认都是从第0个点开始的。
