### ISSUE TITLE
testcase PSO

### ISSUE THREAD

**Issue by shouldsee** [guofei9987/scikit-opt#2]
从 @guofei9987 那搬运一点Rosenbrock function过来？
http://www.guofei.site/2017/06/06/scipyfmin.html

![](http://www.guofei.site/public/postimg/fmin.png)

**Comment by guofei9987** [comment]
为了可以方便地测试不同的优化算法，把GA算法改成求最小值

**Comment by guofei9987** [comment]
http://blog.csdn.net/niuyongjie/article/details/1619496
这里写了一些常用的测试函数
