### ISSUE TITLE
TensorFlow2.0的速度比pytorch更好

### ISSUE THREAD

**Issue by l976308589** [guofei9987/scikit-opt#20]
您好，建议您在0.4版本中使用TensorFlow2.0
其接口做了优化，速度也会提升

**Comment by guofei9987** [comment]
感谢建议！目前仍在这几个架构中做取舍。发布版本会综合考虑性能、稳定性和可扩展性。

**Comment by l976308589** [comment]
应该是感谢您分享如此优秀的项目
我使用cupy+jax复写过您部分代码

**Comment by json007** [comment]
> 应该是感谢您分享如此优秀的项目
> 我使用cupy+jax复写过您部分代码

有个疑问，既然都用了cupy +jax,为啥不选择pytorch,   既有jit, Autograd, 也支持GPU，包含AMD的ROCm

**Comment by l976308589** [comment]
> > 应该是感谢您分享如此优秀的项目
> > 我使用cupy+jax复写过您部分代码
> 
> 有个疑问，既然都用了cupy +jax,为啥不选择pytorch, 既有jit, Autograd, 也支持GPU，包含AMD的ROCm

因为pytorch部署远不如tf2

**Comment by guofei9987** [comment]
> > > 应该是感谢您分享如此优秀的项目
> > > 我使用cupy+jax复写过您部分代码
> > 
> > 
> > 有个疑问，既然都用了cupy +jax,为啥不选择pytorch, 既有jit, Autograd, 也支持GPU，包含AMD的ROCm
> 
> 因为pytorch部署远不如tf2

是这样的
