### ISSUE TITLE
请教多进程模式下，如何释放占用内存

### ISSUE THREAD

**Issue by reborn-sama** [guofei9987/scikit-opt#208]
例如，使用GA优化的多进程模式，
设置 `set_run_mode(worker, 'multiprocessing')`
在数个迭代后会爆内存，是否有方法可以将GA调用的所有内存释放

**Comment by Hayden-CHENPRO** [comment]
这个我现在解决了，得去改源码。scikit-opt 遗传算法里面创建进程池后没有调用pool.close()和pool.join()，导致子进程资源没被释放，在源码的x2y函数里重新实现一下多进程就好了
