### ISSUE TITLE
如何用Anaconda安装这个本地包呢？

### ISSUE THREAD

**Issue by lingr7** [guofei9987/scikit-opt#21]
如题，[Conda 安装本地包 - bitterain - 博客园](https://www.cnblogs.com/bitterain/p/10529030.html)  
找到的方法都是针对`.tar.bz2`的文件

**Comment by guofei9987** [comment]
@lingr7 暂时还不支持conda安装，想手动下载后安装的话，可以下载后用 `pip install .` 来安装
