### ISSUE TITLE
遗传算法解决TSP问题需要改进

### ISSUE THREAD

**Issue by YoshiPark** [guofei9987/scikit-opt#23]
使用scikit-opt的遗传算法模型解决TSP问题时，效果好像不理想，比如stplib数据库里面的att48.tsp时，跑出来的结果跟随机的顺序差不多，att48的链接如下：[http://elib.zib.de/pub/mp-testdata/tsp/tsplib/tsp/att48.tsp](url)
我的参数设置为：
`ga_tsp = GA_TSP(func=cal_total_distance, n_dim=num_points, size_pop=300, max_iter=3000,prob_mut=0.1)`
谢谢

**Comment by YoshiPark** [comment]
这是我实验跑出来的结果：
48 capitals of the US (Padberg/Rinaldi)
Simulated annealing Best distance: 33899.903615127725
Simulated annealing Average distance: 34430.13375274746
Genetic Algorithm Best distance: 87771.26994701447
Genetic Algorithm Average distance: 93383.70990490801
Ant Colony Alogorithm Best distance: 34956.61325328256
Ant Colony Alogorithm Average distance: 35598.34244140098
Solution distance: 33523.70850743559

**Comment by guofei9987** [comment]
`prob_mut` 不宜过大，这个概率代表的是每个基因变异的概率，而不是整条染色体变异的概率。
```python
ga_tsp = GA_TSP(func=cal_total_distance, n_dim=num_points, size_pop=300, max_iter=800, prob_mut=0.001)
```
> distance: 47864.13182497867

有所改进，但效果还是比其它算法差。  
对于较长的路径，GA需要有一些改进策略，这是最近打算做的。

**Comment by guofei9987** [comment]
version 0.5.3 has set the above as default

**Comment by YoshiPark** [comment]
Thank You!

**Comment by guofei9987** [comment]
感谢你提交的bug，是否允许在未来的正式版本 *scikit-opt 1.0* 把你列为 contributor 呢？
