### ISSUE TITLE
算法融合和扩展性

### ISSUE THREAD

**Issue by lensory** [guofei9987/scikit-opt#27]
因为最近在学软计算这门课，有提到算法融合的问题。想了解一下作者是否有实现算法融合的便捷的函数，比如融合遗传算法和模拟退火或者局部梯度下降这些，库里面不知道有没有提供这些接口？另外，不知道蚁群算法里面信息素的相关计算函数有没有快速的自定义方法，可以实现不同策略比如精英蚂蚁、最大最小蚂蚁这些？

**Comment by lensory** [comment]
感谢作者大大了！

**Comment by guofei9987** [comment]
`scikit-opt` 提供了UDF接口，所有算子都可以重写，正好3天前有个案例 #23 

这个案例重写了遗传算法的变异算子，以及重写了一个增强精英策略。

混合算法的话，得具体看怎么混合了，https://github.com/guofei9987/scikit-opt/tree/master/sko/operators 这里提供了一些常见算子，写代码能方便一点儿。
