### ISSUE TITLE
模拟退火SA的问题

### ISSUE THREAD

**Issue by yiwliu** [guofei9987/scikit-opt#29]
```python
import random
import numpy as np
from sko.SA import SA_TSP

def cal_total_distance(routine):
    num_points, = routine.shape
    return sum([distance_matrix[routine[i % num_points], routine[(i + 1) % num_points]] for i in range(num_points)])

num_points = 30
distance_matrix = [ [0] * num_points for _ in range(num_points) ]
for i in range(num_points):
    for j in range(i+1, num_points):
        distance_matrix[i][j] = distance_matrix[j][i] = random.randint(1, num_points)
distance_matrix = np.array(distance_matrix)

sa_tsp = SA_TSP(func=cal_total_distance, x0=range(num_points), T_max=3000, T_min=1, L=10 * num_points)
best_points, best_distance = sa_tsp.run()
print(best_points, best_distance)
```
得到的 best_distance 如图。下图横坐标为迭代次数，纵坐标为cost。
![image](https://user-images.githubusercontent.com/49189394/71582933-38923600-2b47-11ea-93a7-24216fb6881a.png)

**Comment by guofei9987** [comment]
我运行了一下，是下面这样的
```
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)

ax.plot(sa_tsp.best_y_history)
ax.set_xlabel("Distance")
ax.set_ylabel("Iteration")

plt.show()
```

![a](https://user-images.githubusercontent.com/19920283/71585713-7fd1f400-2b52-11ea-982f-2d91aae172b7.png)

**Comment by yiwliu** [comment]
感谢回复🙏
```python
ax.set_xlabel("Distance")
ax.set_ylabel("Iteration")
```
在我这边显示的坐标轴名称是反的。
![image](https://user-images.githubusercontent.com/49189394/72036299-53964000-32d5-11ea-917e-473f842cf21c.png)

-----

#### 我的具体问题第一个issue表示的不明显，抱歉。其实我的问题就是：sa算法使用默认参数执行随机非负距离对称TSP问题，算法陷入局部最优，这种行为是否有问题

#### 以下为问题的具体描述:

* 对于TSP问题使用SA_TSP算法的时候，如果我将30个城市之间的距离随机设置为[1，城市数目]之间的值（对称TSP）。这样的TSP实例的最短路径长度应该在90左右。

* 我是用sa算法默认的参数（最大温度300，最小温度1，L=10*城市个数）初始化类SA，再使用run方法的话，计算出来的实例最短距离（经过了多次执行）大约在230左右。（__算法终止原因为连续max_stay_counter次最优结果未改变__）

* 通过调整参数
   * 将T_max降低为3可以获得接近的90的最优距离（__算法终止原因为达到最低温度T_min__）
   * 更改max_stay_counter基本只会sa算法执行时间，对最优结果没有什么优化

> 本问题可能原因：退火程度问题

**Comment by guofei9987** [comment]
第一个问题：温度的问题（或者说，距离的尺度太小），案例中70个点可以顺利跑出来，是因为进行了进制转换，乘以一万多，你调整完效果应该就完美了。

第二个问题：坐标轴颠倒的问题，我记得一两个星期前修复了


---- 在 星期四, 09 一月 2020 12:39:44 +0800 yiwliu <notifications@github.com> 撰写 ----


感谢回复🙏

ax.set_xlabel("Distance")
ax.set_ylabel("Iteration")


在我这边显示的坐标轴名称是反的。
 https://user-images.githubusercontent.com/49189394/72036299-53964000-32d5-11ea-917e-473f842cf21c.png

我的具体问题第一个issue表示的不明显，抱歉。其实我的问题就是：sa算法使用默认参数执行随机非负距离对称TSP问题，算法陷入局部最优，这种行为是否有问题

以下为问题的具体描述:

对于TSP问题使用SA_TSP算法的时候，如果我将30个城市之间的距离随机设置为[1，城市数目]之间的值（对称TSP）。这样的TSP实例的最短路径长度应该在90左右。


我是用sa算法默认的参数（最大温度300，最小温度1，L=10*城市个数）初始化类SA，再使用run方法的话，计算出来的实例最短距离（经过了多次执行）大约在230左右。（算法终止原因为连续max_stay_counter次最优结果未改变）


通过调整参数

将T_max降低为3可以获得接近的90的最优距离（算法终止原因为达到最低温度T_min）

更改max_stay_counter基本只会sa算法执行时间，对最优结果没有什么优化




本问题可能原因：退火程度问题
