### ISSUE TITLE
能否把自变量约束成整数？

### ISSUE THREAD

**Issue by laokangde** [guofei9987/scikit-opt#30]
在粒子群里，因为我这的自变量是整数的索引，想着如果X以及V都是整数的话，会不会能让算法运行速度更快点？

**Comment by guofei9987** [comment]
可以把 [update_V](https://github.com/guofei9987/scikit-opt/blob/f410e6a6e67e4e0fdd773579559aa8b8b1eaff88/sko/PSO.py#L103), [update_X](https://github.com/guofei9987/scikit-opt/blob/f410e6a6e67e4e0fdd773579559aa8b8b1eaff88/sko/PSO.py#L110) 后面都加上一个 `.astype(np.int)` 但是效果应该很差，回头我找找有没有好一些的论文参考。之前找到一篇论文 Sarman K. Hadia: Solving City Routing Issue with Particle Swarm Optimization ，实现后发现也就维度很低的时候效果还可以。
