### ISSUE TITLE
GA出现超过ub的现象

### ISSUE THREAD

**Issue by l976308589** [guofei9987/scikit-opt#32]
您好，
GA(func=self.fitness,
                n_dim=16,
                size_pop=100,
                max_iter=800,
                lb=[1] * 16,
                ub=[90] * 16,
                precision=1)
按理说ub最大值应该90，但却出现了123,127这种情况

**Comment by guofei9987** [comment]
precision是整数会开启整数规划模式，这时如果候选值的个数不是 2^n ，会自动把搜索空间扩充到2^n并增加一个不等式约束来保证最大值仍然成立。
你的这个情况有16个维度，就会增加16个不等约束，导致搜索空间变得非常受限，如果目标函数稍微复杂一点，就没法很好的计算出来了

**Comment by guofei9987** [comment]
0.5.6之前的版本中，在遗传算法整数规划模式上使用的是罚函数法，极易导致误用和误解，现在已改为更合理的算法逻辑。
