### ISSUE TITLE
多参数算法寻优问题

### ISSUE THREAD

**Issue by clemert** [guofei9987/scikit-opt#33]
你好
现在我有一个函数模型，入参是由多个参数组成的，每个参数可以设置范围（最大值最小值），最后是求最优解所对应的这些入参值，我看了scikit-opt的模拟退火算法和粒子群算法，不知道大佬的算法能不能实现，希望能够解惑一下，感谢！

**Comment by guofei9987** [comment]
目前支持最大值最小值约束的算法：
- 差分进化算法（DE）
- 遗传算法（GA）
- 粒子群算法（PSO）

目前尚不支持最大值最小值约束的算法：
- 模拟退火算法（SA）

有些支持最大值最小值约束的算法，还支持非线性约束
- 差分进化算法（DE）
- 遗传算法（GA）

**Comment by clemert** [comment]
好的，谢谢博主，博主有时间能不能把框架中函数的参数加些注释，有些参数对于第一次接触这些算法的同学来说理解起来有点难度，谢谢啦。
