### ISSUE TITLE
人工鱼群算法的简写

### ISSUE THREAD

**Issue by growvv** [guofei9987/scikit-opt#34]
我发现你的人工鱼群算法简写有好多种，ASFS、ASFA、AFSA，能不能统一下？（虽然问题不大

**Comment by River-Singer** [comment]
不好意思，我是初学者，最近在准备美赛的时候参考了您的代码，对于您的提问我并不了解，非常抱歉。
对了，关于您的蚁群算法以及神经网络算法，我非常的感兴趣，请问您愿意再向我提供一些机器学习的资料或者是源代码吗？
非常感谢！
如有打扰，十分抱歉。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 刘大小<mailto:notifications@github.com>
发送时间: 2020年1月30日 12:36
收件人: guofei9987/scikit-opt<mailto:scikit-opt@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [guofei9987/scikit-opt] 人工鱼群算法的简写 (#34)


我发现你的人工鱼群算法简写有好多种，ASFS、ASFA、AFSA，能不能统一下？（虽然问题不大

―

**Comment by guofei9987** [comment]
> 我发现你的人工鱼群算法简写有好多种，ASFS、ASFA、AFSA，能不能统一下？（虽然问题不大

相当感谢！已统一为 `AFSA`

**Comment by guofei9987** [comment]
> 不好意思，我是初学者，最近在准备美赛的时候参考了您的代码，对于您的提问我并不了解，非常抱歉。 对了，关于您的蚁群算法以及神经网络算法，我非常的感兴趣，请问您愿意再向我提供一些机器学习的资料或者是源代码吗？ 非常感谢！ 如有打扰，十分抱歉。 发送自 Windows 10 版邮件


回复如下：
1. 蚁群算法这一块，我是看 《MATLAB 智能算法-30个案例分析》 这本书，然后写成Python代码的。
2. 这个库不实现神经网络算法。

**Comment by River-Singer** [comment]
非常感谢您的指导！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 郭飞<mailto:notifications@github.com>
发送时间: 2020年2月1日 1:39
收件人: guofei9987/scikit-opt<mailto:scikit-opt@noreply.github.com>
抄送: River-Singer<mailto:allenxujianyang@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [guofei9987/scikit-opt] 人工鱼群算法的简写 (#34)


不好意思，我是初学者，最近在准备美赛的时候参考了您的代码，对于您的提问我并不了解，非常抱歉。 对了，关于您的蚁群算法以及神经网络算法，我非常的感兴趣，请问您愿意再向我提供一些机器学习的资料或者是源代码吗？ 非常感谢！ 如有打扰，十分抱歉。 发送自 Windows 10 版邮件

回复如下：

  1.  蚁群算法这一块，我是看 《MATLAB 智能算法-30个案例分析》 这本书，然后写成Python代码的。
  2.  这个库不实现神经网络算法。

―

**Comment by guofei9987** [comment]
感谢你提交的bug，是否允许在未来的正式版本 *scikit-opt 1.0* 把你列为 contributor 呢？
