### ISSUE TITLE
crossover_pmx 函数value1 与 value2 的位置是不是写反了？

### ISSUE THREAD

**Issue by hranYin** [guofei9987/scikit-opt#36]
./sko/operators/crossover.py 中 的crossover_pmx(self) 函数 
"for j in range(cxpoint1, cxpoint2):
     value1, value2 = Chrom1[j], Chrom2[j]
     pos1, pos2 = pos1_recoder[value1], pos2_recoder[value2] "

第80行代码中的 value1 与 value2 是不是写反了？导致 pos1的value 基本都等于j , 以下swap的时候并未起到交叉的作用。

**Comment by guofei9987** [comment]
感谢！
确实写反了，改正之后测试发现算法的表现反而有所下降，我正在查询相关资料，解决这个问题。

**Comment by hranYin** [comment]
> 感谢！
> 确实写反了，已改正。
> 改正之后测试发现算法的表现反而略有下降，我正在查询相关资料，解决这个问题。
> 
> 另外，您指出的错误很有帮助，如果允许的话，下个版本会把你加入贡献者列表。

可以的， 谢谢您。
