### ISSUE TITLE
the up bounds do not work correctly

### ISSUE THREAD

**Issue by MontyKL** [guofei9987/scikit-opt#37]
when the precision is one, ie. the int_mode is true, the optimized result will lager than the up bounds.

**Comment by MontyKL** [comment]
at GA.py line 154, when you the constriant, the self.has_constriant should be set to TRUE

**Comment by guofei9987** [comment]
Thank you!
You are right, it is a bug. I have fixed it.

- if `precision` is integer:
- if `Lind_raw` is integer, which means the number of all possible value is $2^n$, no need to modify
- if `Lind_raw` is decimal, modify: make the ub bigger and add a constraint_ueq

The fixed version of `scikit-opt` will be released next version, and I‘d like to list you as contributor if you permit.

**Comment by guofei9987** [comment]
Thanks again! And I find more bugs in `int_mode` recently.  
Besides, using penalty function to deal with upper bounds is a bad idea. It causes a lot of misusage and misunderstandings.
I have rebuilt the algorithm by another way in version 0.5.7.

**Comment by Jackwangnao** [comment]
郭老师您好！还想接着问一个整数模式的问题：
int_mode为True是指整数规划模式开启对吧？所以源码中` self.int_mode_ = (self.precision % 1 == 0) & (Lind_raw % 1 != 0) `这里的 `Lind_raw` 应该判断为 `Lind_raw % 1 == 0` 吧？

**Comment by guofei9987** [comment]
> 郭老师您好！还想接着问一个整数模式的问题：
> int_mode为True是指整数规划模式开启对吧？所以源码中`self.int_mode_ = (self.precision % 1 == 0) & (Lind_raw % 1 != 0)`这里的 `Lind_raw` 应该判断为 `Lind_raw % 1 == 0` 吧？

这里代码可能有些歧义，这里的“整数规划模式”指的是需要特别处理才是整数的。如果问题本身不经过特别处理已经是实质上的整数规划，就没必要开启整数规划模式。
