### ISSUE TITLE
请问sko.GA的交叉概率是多少?

### ISSUE THREAD

**Issue by kiritokun07** [guofei9987/scikit-opt#40]
看了`sko.GA`源码，变异概率在`__init__`初始化为`prob_mut=0.001`，交叉概率没有看明白

**Comment by guofei9987** [comment]
默认的算子是按照100%的交叉概率来处理的。
如果不想100%交叉的话，需要自定义交叉算子，参考[UDF](https://scikit-opt.github.io/scikit-opt/#/zh/README?id=%e7%89%b9%e6%80%a71%ef%bc%9audf%ef%bc%88%e7%94%a8%e6%88%b7%e8%87%aa%e5%ae%9a%e4%b9%89%e7%ae%97%e5%ad%90%ef%bc%89)

**Comment by hello726** [comment]
ga = GA(func=demo_func, n_dim=3, size_pop=100, max_iter=500, lb=[-1, -10, -5], ub=[2, 10, 2],
        precision=[1e-7, 1e-7, 1])
这几个调用参数啥意思啊

**Comment by guofei9987** [comment]
`GA.__doc__` 或者 `ga?` 都可以显示文档。
另外，代码注释中也可以看到 https://github.com/guofei9987/scikit-opt/blob/master/sko/GA.py#L98

**Comment by hello726** [comment]
谢谢，我是个初学者(*^▽^*)

**Comment by kiritokun07** [comment]
> ga = GA(func=demo_func, n_dim=3, size_pop=100, max_iter=500, lb=[-1, -10, -5], ub=[2, 10, 2],
> precision=[1e-7, 1e-7, 1])
> 这几个调用参数啥意思啊

我的理解是`func`是定义的目标函数（默认求最小值），`n_dim`是解的维数，`size_pop`是`GA`的种群数量，`max_iter`是最大迭代次数，`lb`和`ub`分别代表解的每一维的下限和上限，`precision`是每一维的精度

**Comment by guofei9987** [comment]
> > ga = GA(func=demo_func, n_dim=3, size_pop=100, max_iter=500, lb=[-1, -10, -5], ub=[2, 10, 2],
> > precision=[1e-7, 1e-7, 1])
> > 这几个调用参数啥意思啊
> 
> 我的理解是`func`是定义的目标函数（默认求最小值），`n_dim`是解的维数，`size_pop`是`GA`的种群数量，`max_iter`是最大迭代次数，`lb`和`ub`分别代表解的每一维的下限和上限，`precision`是每一维的精度

是这样的
