### ISSUE TITLE
How can I add complex constraints?

### ISSUE THREAD

**Issue by Tang115** [guofei9987/scikit-opt#41]
For example, my optimization problem is as follows:

min mean(x)
s.t. 1< function(x) < 5

The "function()" is a function using "x" as input defined by myself.

Let's say DE algorithm.

**Comment by guofei9987** [comment]
see [this](https://scikit-opt.github.io/scikit-opt/#/en/README?id=_1-differential-evolution)  

```
constraint_ueq = [
    lambda x: 1 - function(x),
    lambda x: function(x) - 5
]
```
