### ISSUE TITLE
遗传算法要是可以多线程就好了

### ISSUE THREAD

**Issue by bnpzsx** [guofei9987/scikit-opt#43]
单次计算适应度耗时太长

**Comment by guofei9987** [comment]
事实上是支持矢量化运算的：
- 大多数默认算子直接支持矢量化运算
- 适应度计算支持矢量化计算，但默认设定为否，这是考虑到新手用户会编程中出错。参看[文档](https://scikit-opt.github.io/scikit-opt/#/zh/speed_up?id=%e7%9f%a2%e9%87%8f%e5%8c%96%e8%ae%a1%e7%ae%97)
- 经过实验，多线程的实际速度远不如矢量化运算，因此做了删除处理。这是因为，作为纯 Python实现，多线程优化途径很受限。相比之下，矢量化运算充分利用了 numpy 的矢量化计算能力。
- 另外，还实现了利用 Pytorch 的 GPU 计算能力的代码，参见 [文档](https://scikit-opt.github.io/scikit-opt/#/zh/README?id=%e7%89%b9%e6%80%a72-gpu-%e5%8a%a0%e9%80%9f)。但实验发现，只有计算量极大的时候，才比矢量化计算快。

**Comment by bnpzsx** [comment]
非常感谢，开启矢量化计算后，在适应度函数里加上多线程就就很快了

**Comment by MacsYan** [comment]
适应度函数本身不支持全部矢量化计算，可以使用numba对局部numpy计算加速。怎样开启多线程加速呢

**Comment by bnpzsx** [comment]
这里我使用的进程池，每次计算适应度就分配一个任务

**Comment by shiyunlai233** [comment]
> 这里我使用的进程池，每次计算适应度就分配一个任务

具体怎么做呢？是否能直接给个代码示例？

**Comment by guofei9987** [comment]
0.6.2 版本已经支持以下加速：

- 并行化计算
- 矢量化计算
- 缓存化计算


中文文档： https://scikit-opt.github.io/scikit-opt/#/zh/speed_up
英文文档：https://scikit-opt.github.io/scikit-opt/#/en/speed_up

如有建议，欢迎重新 open issue～
