### ISSUE TITLE
模拟退火算法扰动的上下界有问题

### ISSUE THREAD

**Issue by zhangcogito** [guofei9987/scikit-opt#45]
在模拟退火算法的SAFast类中
```
class SAFast(SimulatedAnnealingBase):
    def __init__(self, func, x0, T_max=100, T_min=1e-7, L=300, max_stay_counter=150, **kwargs):
        super().__init__(func, x0, T_max, T_min, L, max_stay_counter, **kwargs)
        self.m, self.n, self.quench = kwargs.get('m', 1), kwargs.get('n', 1), kwargs.get('quench', 1)
        self.lower, self.upper = kwargs.get('m', -10), kwargs.get('m', 10)
        self.c = self.m * np.exp(-self.n * self.quench)
    def get_new_x(self, x):
        r = np.random.uniform(-1, 1, size=self.n_dims)
        xc = np.sign(r) * self.T * ((1 + 1.0 / self.T) ** np.abs(r) - 1.0)
        x_new = x + xc * (self.upper - self.lower)
        return x_new

    def cool_down(self):
        self.T = self.T_max * np.exp(-self.c * self.iter_cycle ** self.quench)
```
初始化函数根据参数确定扰动的lower和upper时，使用的都是关键字参数'm'，这个地方是不是写错了，如果我传入一个参数m，岂不是lower和upper都是同一个值了。而且在SABoltzmann类中也存在同样的问题。我安装的版本是0.5.5

**Comment by guofei9987** [comment]
感谢！
- 今晚修复
- 是否允许在1.0正式版本，把你列为 contributor？

**Comment by zhangcogito** [comment]
很荣幸能做一点小贡献，如果可以列为contributor我也不胜感激


 
---原始邮件---
发件人: "郭飞"<notifications@github.com&gt;
发送时间: 2020年4月18日 22:56:19
收件人: "guofei9987/scikit-opt"<scikit-opt@noreply.github.com&gt;;
抄送: "zhangqiangbing"<2752067558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [guofei9987/scikit-opt] 模拟退火算法扰动的上下界有问题 (#45)




 
感谢！
  
今晚修复 

是否允许在1.0正式版本，把你列为 contributor？
