### ISSUE TITLE
遗传算法用于大规模的0-1整数规划可行吗？

### ISSUE THREAD

**Issue by Do-no-evil** [guofei9987/scikit-opt#46]
新手，现在想做一个800多个变量的0-1整数规划，想利用遗传算法实现，这样运算会不会很慢？

**Comment by guofei9987** [comment]
参见 [文档](https://scikit-opt.github.io/scikit-opt/#/zh/more_ga?id=%e9%81%97%e4%bc%a0%e7%ae%97%e6%b3%95%e8%bf%9b%e8%a1%8c%e6%95%b4%e6%95%b0%e8%a7%84%e5%88%92)  

- 运算速度不会变太慢
- 能不能算出全局最优取决于目标函数是否适合用遗传算法来求解。
