### ISSUE TITLE
参数lb和ub的含义，还有怎么提供自己的初始种群？

### ISSUE THREAD

**Issue by 1158755456** [guofei9987/scikit-opt#49]
ga = GA(func=demo_func, n_dim=3, size_pop=100, max_iter=500, lb=[-1, -10, -5], ub=[2, 10, 2], precision=[1e-7, 1e-7, 1])
 这句代码里面的上下界lb ub 意思是 x0 [-1,2) x1[-10,10) x2[-5,2) 这样吗？
如果我想自己提供初始种群怎么做呢？

**Comment by guofei9987** [comment]
1. 上下界的理解是对的
2. 在创建 `ga` 对象后，可以把 `ga.Chrom` 赋值为自定义种族。例如 `ga.Chrom = np.random.randint(0,2,size=(80,20))`

**Comment by 1158755456** [comment]
谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"郭飞"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 中午12:46
收件人:&nbsp;"guofei9987/scikit-opt"<scikit-opt@noreply.github.com&gt;;
抄送:&nbsp;"风飞沙"<1158755456@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guofei9987/scikit-opt] 参数lb和ub的含义，还有怎么提供自己的初始种群？ (#49)





  
上下界的理解是对的
 
在创建 ga 对象后，可以把 ga.Chrom 赋值为自定义种族。例如 ga.Chrom = np.random.randint(0,2,size=(80,20))
