### ISSUE TITLE
这就是所谓的“最好”？希望您还是直接调用权威一点的框架吧

### ISSUE THREAD

**Issue by gongyongq** [guofei9987/scikit-opt#5]
希望不要进行虚假宣传，说自己写的库是“最好”的，人外有人天外有天。比如跑一下这个简单的TSP问题，设置100个体、2000代进化，您所谓的“最好”的库结果如下：
![image](https://user-images.githubusercontent.com/53175954/64472278-82b56d00-d18e-11e9-873d-9a1b1827de0b.png)

而直接调用权威框架的结果：

![image](https://user-images.githubusercontent.com/53175954/64472283-952fa680-d18e-11e9-9c05-b6c7901716e1.png)

**Comment by guofei9987** [comment]
可以这样改进
1. 提高 Pm(变异概率)。因为链越长，每个基因分摊到的变异概率越低。另一个库针对变异概率做了线性的调整，而这个库仍然引用传统的变异概率的定义。*（以后版本会考虑是否也进行线性调整，不过未必会这么做）*
2. 提高迭代次数。因为发现迭代到快2000次时，适应度曲线仍然在上升。这里的差别主要来自另一个库针对长链TSP进行了特殊改进，具体来说是改进了 `selection` 算子。

例如，下面提高变异概率，提高迭代次数，并且 `selection` 算子改为“精英保留策略”（这个算子也不是针对长链TSP问题的，不过凑合用吧）


```
from sko.GA import GA_TSP

def selection_elite(self, FitV):
    # print('udf selection actived')

    FitV = (FitV - FitV.min()) / (FitV.max() - FitV.min() + 1e-10) + 0.2
    # the worst one should still has a chance to be selected
    # the elite(defined as the best one for a generation) must survive the selection
    elite_index = np.array([FitV.argmax()])

    # do Roulette to select the next generation
    sel_prob = FitV / FitV.sum()
    roulette_index = np.random.choice(range(self.size_pop), size=self.size_pop - 1, p=sel_prob)
    sel_index = np.concatenate([elite_index, roulette_index])
    self.Chrom = self.Chrom[sel_index, :]  # next generation
    return self.Chrom


GA_TSP.selection = selection_elite

ga_tsp = GA_TSP(func=cal_total_distance, n_dim=num_points, pop=100, max_iter=20000, Pm=0.9)
best_points, best_distance = ga_tsp.fit()
```

![Figure_1](https://user-images.githubusercontent.com/19920283/64475014-5b22cc80-d1af-11e9-918d-74f0358994c2.png)

至于  `selection` 算子 的改进，不出意外会在0.3版本之后上线，到时候针对长链TSP的效果会好很多。  

这个库兼顾代码简洁性、代码可读性、结果可用性、对原理的忠实。对比所谓“权威”库是不是最好就见仁见智了。毕竟有了MySQL还需要Spark不是吗。

**Comment by guofei9987** [comment]
另外，感谢提出问题，并且欢迎继续多提问题 @gongyongq

**Comment by gongyongq** [comment]
> 另外，感谢提出问题，并且欢迎继续多提问题 @gongyongq

我都不敢再提问题了，只要一提问题，连完整的问题描述都被你修改了。言论自由都没有。摊手。

**Comment by gongyongq** [comment]
> 可以这样改进
> 
> 1. 提高 Pm(变异概率)。因为链越长，每个基因分摊到的变异概率越低。另一个库针对变异概率做了线性的调整，而这个库仍然引用传统的变异概率的定义。_（以后版本会考虑是否也进行线性调整，不过未必会这么做）_
> 2. 提高迭代次数。因为发现迭代到快2000次时，适应度曲线仍然在上升。这里的差别主要来自另一个库针对长链TSP进行了特殊改进，具体来说是改进了 `selection` 算子。
> 
> 例如，下面提高变异概率，提高迭代次数，并且 `selection` 算子改为“精英保留策略”（这个算子也不是针对长链TSP问题的，不过凑合用吧）
> 
> ```
> from sko.GA import GA_TSP
> 
> def selection_elite(self, FitV):
>     # print('udf selection actived')
> 
>     FitV = (FitV - FitV.min()) / (FitV.max() - FitV.min() + 1e-10) + 0.2
>     # the worst one should still has a chance to be selected
>     # the elite(defined as the best one for a generation) must survive the selection
>     elite_index = np.array([FitV.argmax()])
> 
>     # do Roulette to select the next generation
>     sel_prob = FitV / FitV.sum()
>     roulette_index = np.random.choice(range(self.size_pop), size=self.size_pop - 1, p=sel_prob)
>     sel_index = np.concatenate([elite_index, roulette_index])
>     self.Chrom = self.Chrom[sel_index, :]  # next generation
>     return self.Chrom
> 
> 
> GA_TSP.selection = selection_elite
> 
> ga_tsp = GA_TSP(func=cal_total_distance, n_dim=num_points, pop=100, max_iter=20000, Pm=0.9)
> best_points, best_distance = ga_tsp.fit()
> ```
> 
> ![Figure_1](https://user-images.githubusercontent.com/19920283/64475014-5b22cc80-d1af-11e9-918d-74f0358994c2.png)
> 
> 至于 `selection` 算子 的改进，不出意外会在0.3版本之后上线，到时候针对长链TSP的效果会好很多。
> 
> 这个库兼顾代码简洁性、代码可读性、结果可用性、对原理的忠实。对比所谓“权威”库是不是最好就见仁见智了。毕竟有了MySQL还需要Spark不是吗。

这个回答让我看到你对于这个领域是相当的业余。你先去看看论文，再看看别的库的源码，看看到底用的是不是标准的普通的、非自适应的变异概率；看看别人的算法到底是不是标准的、到底是不是和参考文献一致的。人家deap可是知名实验室做出来的，里面的算法都有论文严格支撑。

其实你不自己鼓吹自己写的库是”最好“的，我也不会来提出让你为难的问题。学术界是严肃的，绝不容许自吹自擂。人家deap也不自吹”最强“，你这个库连效果都不行的你怎么敢说”最好“？
