### ISSUE TITLE
May Class "GeneticAlgorithmBase" have "precision" Attribute?

### ISSUE THREAD

**Issue by FelixLukk** [guofei9987/scikit-opt#50]
Firstly, I have to say It's an extremely Great package, and thanks for your work.

Well, let's go back to my case. I am using DifferentialEvolution algorithm to solve LingerPrograming problems. The algorithm is OK and powerful, without doubt. 

However, when I wanna to solve Integer LingerPrograming, I figure out that "GeneticAlgorithmBase" class does not have "precision" attribute as GA has.

That is my problem , and now I am working on adding "precision" attribute to "GAbase".

Over all, here is just a suggestion to implement  "precision"  on "GAbase" Class. 
Since I don't know what is your specific requirement or which detail you concern about. Maybe we could discuss about that, My feedback is just a suggestion anyway.

**Comment by guofei9987** [comment]
Thank you for your suggestion. It is very helpful.  

Yes, adding `precision` attribute to `GeneticAlgorithmBase` and deleting if from `GA` is an improvement.  
To do that, the first step is to let the package support "Integer LingerPrograming problems" in "DifferentialEvolution algorithm". I always wanted to do that but was busy with other work.  

Maybe I can do this in the near future. Some help or contribution to the codes is also welcome.

**Comment by FelixLukk** [comment]
Sorry for the late reply. 

I am glad and hoping for the latest modification. Thanks for your work again.
