### ISSUE TITLE
约束关系没有发挥作用

### ISSUE THREAD

**Issue by MacsYan** [guofei9987/scikit-opt#52]
非常感谢您的及时回答。
您好，我使用demo中约束关系列表为差分算法施加了约束关系，但是计算出来的结果好像约束关系没有发挥作用。
    constraint_ueq = []
    for i in range(16):
        for j in range(15):
            constraint_ueq.append(lambda x: x[0 + j+i*16] - x[1 + j+i*16])
    for i in range(16):
        for j in range(15):
            constraint_ueq.append(lambda x:x[0+j*16+i] - x[16+j*16+i])
    for i in range(6):
        constraint_ueq.append(lambda x:x[256+i] - x[257+i])
    for i in range(11):
        constraint_ueq.append(lambda x:x[264+i] - x[263+i])
我在做一个汽车系统的自动标定，涉及到一个256的曲面和一个7的曲线，12的曲线。
曲面自身和曲线自身有平顺性的要求（沿x轴和y轴递增），所以我用以上关系施加了不等式约束，但是优化出来的结果，好像没有反应出这种约束关系。我查看了差分算法的源代码，使用的是罚函数做约束施加？代码如下？
        if not self.has_constraint:
            self.Y = self.Y_raw
        else:
            # constraint
            penalty_eq = np.array([np.sum(np.abs([c_i(x) for c_i in self.constraint_eq])) for x in self.X])
            penalty_ueq = np.array([np.sum(np.abs([max(0, c_i(x)) for c_i in self.constraint_ueq])) for x in self.X])
            self.Y = self.Y_raw + 1e5 * penalty_eq + 1e5 * penalty_ueq
请问如何让我的约束关系在算法的种群生成，变异、交叉、选择中发挥作用？
非常感谢您的及时回答。

**Comment by MacsYan** [comment]
[工程师标定数据与算法自动标定数据对比.xlsx](https://github.com/guofei9987/scikit-opt/files/4598663/default.xlsx)
附件是算法优化的结果和工程师手动计算的结果；我希望算法的结果能够满足曲面和曲线的平顺性要求，也就是沿x轴和y轴递增或递减。

**Comment by guofei9987** [comment]
`constraint_eq` 和 `constraint_ueq` 是使用罚函数法来实现约束的，如果数量过多会导致搜索空间过于狭窄从而无法收敛。  
尽量用变量替换法，把不等号变换到单变量上，然后用 `lb` 和 `ub`

**Comment by MacsYan** [comment]
谢谢回复。
请问用变量替换法，把不等号变换到单变量上，然后用 lb 和 ub怎样理解，如何在程序中实现。
另外可以考虑在初始化、变异过程中把约束关系加上去发挥作用吗？

**Comment by guofei9987** [comment]
例如，原约束是 `x1+x2<3`，那么可以用 `y1=x1+x2`，然后用 `y1` 做优化，`ub=3`  
lb和ub是下限和上限，在各个算子中起作用。

**Comment by MacsYan** [comment]
我的目标是这样的，x1<x2, x2<x3, x3<x4........就是点与点之间存在着大量的不等式关系。好像难以使用单变量替换法做优化。

**Comment by guofei9987** [comment]
用线性代数的方法，矩阵初等变换

**Comment by MacsYan** [comment]
我还是有点不太明白，怎样试用矩阵初等变化，让我的约束关系发挥作用。
现在差分算法还是很高效的，能够很快收敛到工程目标，但是就是给出的曲面和曲线的平顺性不行，也就是不能满足沿x轴y轴递增和递减关系。
如果约束关系这个问题能解决就非常棒了。

**Comment by MacsYan** [comment]
我明白你的意思了。就是用点与点之间差值作为算法调整的种群，然后把约束关系转变为与0的关系。
我按照你说的试了一下，优化不下去呀，用原来的数据能很快的优化到目标结果，用差值完全优化不动。

**Comment by guofei9987** [comment]
尽量用 `lb` 和 `ub`，这两个变量是作为变量的下限和上限，这两个约束是嵌入在算子中的，很有效。 
 
尽量不要用 `constraint_eq ` 和 `constraint_ueq`， 这两个只是作为补充措施，数量少的时候才可以发挥作用。  

如果约束关系都是线性的话，可以用线性代数方法（消元法，或者矩阵的初等变换），自变量约束变成 `lb<x1<ub` 这种形式

**Comment by MacsYan** [comment]
我的模型里面要求的点与周围的点之间都有约束。使用差值变换只能保证一个方向的约束关系，另一个方向的约束没法满足。可以在算法中考虑使用可行域来处理约束吗

**Comment by guofei9987** [comment]
如果约束都是线性的，可以用线性代数的方法转为`lb` 和 `ub` 的形式，具体看这里  https://www.guofei.site/2017/06/12/linearprogramming.html 
（国内网络连接不一定很顺畅，多刷新几次）
