### ISSUE TITLE
Want to set up starting point

### ISSUE THREAD

**Issue by rayjan0114** [guofei9987/scikit-opt#54]
Thanks for the great work of this repo!

Wish to have enhancement for letting us set up a starting point of the parameters that we want to optimize

**Comment by guofei9987** [comment]
Maybe already have!
For `GA`, after `ga=GA(**params)`, use codes like `ga.Chrom = np.random.randint(0,2,size=(80,20))` to manually set the initial population.  

For `DE`, set `de.X` to your initial X.  

For `PSO`, set `pso.X` to your initial X, and run `pso.cal_y()`. I realize just now that it is not good enough. May be `pso.cal_y()` can be omitted in the future version.  

For `SA`, there is a parameter `x0`, which is the init point.

**Comment by morestart** [comment]
终点能不能设置呢？
