### ISSUE TITLE
关于参数传递

### ISSUE THREAD

**Issue by hadlang** [guofei9987/scikit-opt#57]
官方的示例是这样的，
def demo_func(x):
    x1, x2, x3 = x
    return x1**2+x2*1+x3
如果我的目标函数是类似于这样的：
def demo_func(x,model,y):
    x1,x2,x3=x
    model,y 是我要传递的其他参数，请问该怎么写
PSO(func=demo_func, dim=3, pop=40, max_iter=150, lb=[0, -1, 0.5], ub=[1, 1, 1], w=0.8, c1=0.5, c2=0.5) 这个里面的demo_func.

**Comment by guofei9987** [comment]
包装一层
```python
def your_func(x, model, y):
    return x+model+y

def demo_func(t):
    x, model, y = t
    return your_func(x, model, y)
```

**Comment by hadlang** [comment]
不好意思，我没看懂。我的意思是我调用PSO的时候，怎么把x, model, y这三个传给demo_func()，也就是这个参数t在主函数里怎么构造。

**Comment by guofei9987** [comment]
如果model和y是其它地方定义的，
```
model = 's'
y = 1

def your_func(x, model, y):
    x1, x2, x3 = x
    if model == 's':
        return x1 + x2 + x3 + y
    else:
        return x1 + x2 - x3 - y
```
那么你在调用 scikit-opt 的时候，需要在外面封装一层

```
def demo_func(x):
    x1, x2, x3 = x
    return your_func(x, model, y)
```

然后把 demo_func 放入 scikit-opt 计算
```
PSO(func=demo_func, **params)
```

**Comment by hadlang** [comment]
明白了，非常感谢

**Comment by KCWang010** [comment]
下面是我根据上面的代码写的程序，但是存在两个问题：
1. 该程序会报错：ValueError: not enough values to unpack (expected 3, got 1)
2. 并没有把main函数中的model和y传给demo_func()
恳请好心人给小白指点迷津，感激不尽！

from sko.GA import GA

def your_func(x, model, y):
    return x + model + y

def demo_func(t):
    x, model, y = t
    return your_func(x, model, y)

def main():
    model = 's'
    y = 1

    ga = GA(func=demo_func, n_dim=1, size_pop=10, max_iter=50)

    best_params, residuals = ga.run()
    print('best_x:', best_params, '\n', 'best_y:', residuals)

if __name__ == "__main__":
    main()
