### ISSUE TITLE
crossover.crossover_1point单点交叉这里的代码有点小bug

### ISSUE THREAD

**Issue by rqhu1995** [guofei9987/scikit-opt#60]
crossover.py的第9行：
`n = np.random.randint(0, self.len_chrom, 1)`
调试的时候看到这里的n是一个1*1的向量[n]，而不是标量。
后面执行到11和12行：
`seg1, seg2 = self.Chrom[i, n:].copy(), self.Chrom[i + 1, n:].copy()`
`self.Chrom[i, n:], self.Chrom[i + 1, n:] = seg2, seg1`
就会报错说only integer scalar arrays can be converted to a scalar index
应该是说这里的n不能作为索引？

在crossover_2point没有这个问题，因为那边的
`n1, n2 = np.random.randint(0, self.len_chrom, 2)`
确实是生成两个标量赋值给n1和n2。

ga.register使用单点交叉的时候报了错，所以觉得这边是不是有点问题。

**Comment by guofei9987** [comment]
感谢！确实是bug
