### ISSUE TITLE
请问如何估计时间呢 GA 和 PSO

### ISSUE THREAD

**Issue by zhuangjunfei1012** [guofei9987/scikit-opt#61]
想估计程序整体运行完所需要的时间，GA和PSO应该怎么估计呢

**Comment by guofei9987** [comment]
这个库本身不提供估计时间的功能，如果想要估计，可以用下面的方法：
1. Pycharm自带的profile功能
2. 找到源代码中的 `run` 函数，在for循环中打印时间

我之前的测试，如果速度慢的话，基本是慢在目标函数值的计算上了。
1. 目标函数值计算这一块，目前已经支持矢量化计算，推荐优先使用。
2. 早期的版本还支持并行运算，但由于线程通讯的问题，速度基本上反而是下降的，所以删掉了这个功能。但最近有人反馈说，对于十分复杂的目标函数，并行还是可以加快速度的，最近准备抽空把这个功能补上。
