### ISSUE TITLE
算法参数问题

### ISSUE THREAD

**Issue by DingSizhe** [guofei9987/scikit-opt#64]
您好！请问当用户没有指定一些模型参数（例如GA里的交叉概率、变异概率等）时，程序将使用何种策略自动选择这些参数呢？
谢谢解答！

**Comment by guofei9987** [comment]
默认参数：GA交叉概率1，变异概率0.001，可以在源码中看到。
不过确实应当在文档中明确写出来。所以计划在下一个版本的文档中详细列出来。

**Comment by guofei9987** [comment]
- 参数说明的中文文档已更新 https://scikit-opt.github.io/scikit-opt/#/zh/args
- 英文文档正在路上

**Comment by guofei9987** [comment]
英文文档已有 https://scikit-opt.github.io/scikit-opt/#/en/args
