### ISSUE TITLE
神经网络算法求一元变量最小值出现的问题

### ISSUE THREAD

**Issue by 644163476** [guofei9987/scikit-opt#65]
def fun(t):
    x1=t
    v =           (rs_blue-((constant[0]+constant[1]*(bw[1]+q*(constant[6]/ag[2])**c)   /(   (bw[1]+q*(constant[6]/ag[2])**c) + aw[1] + (aphy[2]+aphy[3]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[2]-constant[8]))   )     )*(bw[1]+q*(constant[6]/ag[2])**c)   /(   (bw[1]+q*(constant[6]/ag[2])**c) + aw[1] + (aphy[2]+aphy[3]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[2]-constant[8]))   ) *(constant[7]-np.e**(     -(    1/np.cos(angle[0])   + (constant[2]*(constant[7]+constant[3]*(bw[1]+q*(constant[6]/ag[2])**c)   /(   (bw[1]+q*(constant[6]/ag[2])**c) + aw[1] + (aphy[2]+aphy[3]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[2]-constant[8]))   ))**0.5)) * (    aw[1] + (aphy[2]+aphy[3]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[2]-constant[8]))    )* (bw[1]+q*(constant[6]/ag[2])**c) *x1  )    )+ B[0]*np.e**(     -(    1/np.cos(angle[0])   + (constant[4]*(constant[7]+constant[5]*(bw[1]+q*(constant[6]/ag[2])**c)   /(   (bw[1]+q*(constant[6]/ag[2])**c) + aw[1] + (aphy[2]+aphy[3]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[2]-constant[8]))   ))**0.5)) * (    aw[1] + (aphy[2]+aphy[3]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[2]-constant[8]))    )* (bw[1]+q*(constant[6]/ag[2])**c) *x1  )  ) )**2 +\
				  (rs_green-((constant[0]+constant[1]*(bw[2]+q*(constant[6]/ag[3])**c)   /(   (bw[2]+q*(constant[6]/ag[3])**c) + aw[2] + (aphy[4]+aphy[5]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[3]-constant[8]))   )     )*(bw[2]+q*(constant[6]/ag[3])**c)   /(   (bw[2]+q*(constant[6]/ag[3])**c) + aw[2] + (aphy[4]+aphy[5]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[3]-constant[8]))   ) *(constant[7]-np.e**(     -(    1/np.cos(angle[0])   + (constant[2]*(constant[7]+constant[3]*(bw[2]+q*(constant[6]/ag[3])**c)   /(   (bw[2]+q*(constant[6]/ag[3])**c) + aw[2] + (aphy[4]+aphy[5]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[3]-constant[8]))   ))**0.5)) * (    aw[2] + (aphy[4]+aphy[5]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[3]-constant[8]))    )* (bw[2]+q*(constant[6]/ag[3])**c) *x1  )    )+ B[1]*np.e**(     -(    1/np.cos(angle[0])   + (constant[4]*(constant[7]+constant[5]*(bw[2]+q*(constant[6]/ag[3])**c)   /(   (bw[2]+q*(constant[6]/ag[3])**c) + aw[2] + (aphy[4]+aphy[5]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[3]-constant[8]))   ))**0.5)) * (    aw[2] + (aphy[4]+aphy[5]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[3]-constant[8]))    )* (bw[2]+q*(constant[6]/ag[3])**c) *x1  )  ) )**2 +\
				  (rs_red-((constant[0]+constant[1]*(bw[3]+q*(constant[6]/ag[4])**c)   /(   (bw[3]+q*(constant[6]/ag[4])**c) + aw[3] + (aphy[6]+aphy[7]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[4]-constant[8]))   )     )*(bw[3]+q*(constant[6]/ag[4])**c)   /(   (bw[3]+q*(constant[6]/ag[4])**c) + aw[3] + (aphy[6]+aphy[7]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[4]-constant[8]))   ) *(constant[7]-np.e**(     -(    1/np.cos(angle[0])   + (constant[2]*(constant[7]+constant[3]*(bw[3]+q*(constant[6]/ag[4])**c)   /(   (bw[3]+q*(constant[6]/ag[4])**c) + aw[3] + (aphy[6]+aphy[7]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[4]-constant[8]))   ))**0.5)) * (    aw[3] + (aphy[6]+aphy[7]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[4]-constant[8]))    )* (bw[3]+q*(constant[6]/ag[4])**c) *x1  )    )+B[2]*np.e**(     -(    1/np.cos(angle[0])   + (constant[4]*(constant[7]+constant[5]*(bw[3]+q*(constant[6]/ag[4])**c)   /(   (bw[3]+q*(constant[6]/ag[4])**c) + aw[3] + (aphy[6]+aphy[7]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[4]-constant[8]))   ))**0.5)) * (    aw[3] + (aphy[6]+aphy[7]*np.log(p) )*p +  g*np.e**(ag[0]* (ag[4]-constant[8]))    )* (bw[3]+q*(constant[6]/ag[4])**c) *x1  )  ) )**2

    return v

    ga = GA(func=fun, n_dim=1, size_pop=30, max_iter=100, lb=0.1, ub=20, precision=1e-7)
    best_x, best_y = ga.run()

erro：  File "F:/Users/dell/PycharmProjects/untitled9/非线性优化.py", line 125, in <module>
    best_x, best_y = ga.run()
  File "C:\Users\dell\Anaconda3\lib\site-packages\sko\GA.py", line 80, in run
    self.crossover()
  File "C:\Users\dell\Anaconda3\lib\site-packages\sko\operators\crossover.py", line 44, in crossover_2point_bit
    Chrom1 ^= mask2
ValueError: non-broadcastable output operand with shape (15,1,28) doesn't match the broadcast shape (15,15,28)

有懂的么，是这个神经网络就不能用一元变量么  如果是二元就可以 我也不知道是为啥

**Comment by guofei9987** [comment]
一元变量也要按二元变量的格式来处理。  
第二行 `x1=t` 改为 `x1, = t`
