### ISSUE TITLE
再用您的遗传算法求非线性目标函数的最小值时，设置完边界后，求得最优结果总是靠近边界，用python自带的全局最优basinhooping就不会产生该问题，不知是否是我在使用你的遗传算法时，参数设置有问题，能否提醒一下，该设置哪些参数

### ISSUE THREAD

**Issue by 644163476** [guofei9987/scikit-opt#66]

**Comment by guofei9987** [comment]
代码贴上来看看

**Comment by 644163476** [comment]
def fun(p):
    x1,=p
    a=np.zeros(3)
    a[0]=aw[1] + (aphy[2]+aphy[3]*np.log(x1) )*0.06678057 + 0.01962858*np.e**(ag[0]* (ag[2]-constant[8]))
    a[1]=aw[2] + (aphy[4]+aphy[5]*np.log(x1) )*0.06678057 +  0.01962858*np.e**(ag[0]* (ag[3]-constant[8]))
    a[2]=aw[3] + (aphy[6] + aphy[7] * np.log(x1)) * 0.06678057 + 0.01962858 * np.e ** (ag[0] * (ag[4] - constant[8]))
    b=np.zeros(3)
    b[0]=bw[1]+0.00275185*(constant[6]/ag[2])**1.9
    b[1]=bw[2]+0.00275185*(constant[6]/ag[3])**1.9
    b[2]=bw[3]+0.00275185*(constant[6]/ag[4])**1.9
    u=np.zeros(3)
    u[0] = b[0] / (b[0] + a[0])
    u[1] = b[1] / (b[1] + a[1])
    u[2] = b[2] / (b[2] + a[2])
    rs_deep=np.zeros(3)
    rs_deep[0] = (0.084 + 0.17 * u[0]) * u[0]
    rs_deep[1] = (0.084 + 0.17 * u[1]) * u[1]
    rs_deep[2] = (0.084 + 0.17 * u[2]) * u[2]
    Duc=np.zeros(3)
    Duc[0]=1.03*(1+2.4*u[0])**0.5
    Duc[1] = 1.03 * (1 + 2.4 * u[1]) ** 0.5
    Duc[2] = 1.03 * (1 + 2.4 * u[2]) ** 0.5
    Dub = np.zeros(3)
    Dub[0]=1.10*(1+5*u[0])**0.5
    Dub[1] = 1.10 * (1 + 5 * u[1]) ** 0.5
    Dub[2] = 1.10 * (1 + 5 * u[2]) ** 0.5
    k=np.zeros(3)
    k[0]=a[0]*b[0]
    k[1] = a[1] * b[1]
    k[2] = a[2] * b[2]



    v=(rs_blue-(rs_deep[0]*(1-np.e**((-1)*(1/np.cos(20.02)+Duc[0])*k[0]*x1))+B[0]*np.e**((-1)*(1/np.cos(20.02)+Dub[0])*k[0]*x1)))**2 + \
      (rs_green - (rs_deep[1] * (1 - np.e ** ((-1) * (1 / np.cos(20.02) + Duc[1]) * k[1] * x1)) + B[1] * np.e ** ((-1) * (1 / np.cos(20.02) + Dub[1]) * k[1] * x1))) ** 2 + \
      (rs_red - (rs_deep[2] * (1 - np.e ** ((-1) * (1 / np.cos(20.02) + Duc[2]) * k[2] * x1)) + B[2] * np.e ** ((-1) * (1 / np.cos(20.02) + Dub[2]) * k[2] * x1))) ** 2
    return v

for m in range(50):
    rs_blue = Rs_blue[m]
    rs_green = Rs_green[m]
    rs_red = Rs_red[m]
    ga = GA(func=fun, n_dim=1, size_pop=30, max_iter=250, lb=[0.9], ub=[20], precision=1e-7)
    best_x, best_y = ga.run()
    print('best_x:', best_x, '\n', 'best_y:', best_y)
    print(datamat[list1[m], 2])
用您的神经网络结果基本都在边界
输出：best_x: [0.90116698] 
 best_y: [2.02930868e-05]
0.9
best_x: [0.90000142] 
 best_y: [2.30848933e-05]
9.6
best_x: [0.90714028] 
 best_y: [0.00078638]
3.2
best_x: [0.9] 
 best_y: [1.63561559e-05]
6.4
best_x: [0.9] 
 best_y: [6.99757984e-05]
8.4
best_x: [20.] 
 best_y: [1.63666797e-05]
13.2
best_x: [0.93925727] 
 best_y: [3.8250736e-05]
9.4
best_x: [0.90233176] 
 best_y: [0.00117587]
2.9
best_x: [0.90510039] 
 best_y: [0.00138267]
3.3
best_x: [0.93730469] 
 best_y: [1.79938952e-05]
7.7
best_x: [0.90174887] 
 best_y: [1.46022148e-05]
12.3
best_x: [0.90004554] 
 best_y: [2.19364929e-05]
10.3
best_x: [0.9003421] 
 best_y: [0.00016385]
7.5
best_x: [0.90000007] 
 best_y: [2.88911164e-05]
4.8
best_x: [0.91899665] 
 best_y: [4.45177598e-05]
8.4
best_x: [0.90994478] 
 best_y: [2.71982951e-05]
12.7
best_x: [0.90002071] 
 best_y: [0.0013502]

**Comment by guofei9987** [comment]
完整贴一下，aphy，aw，Rs_blue

还有basinhooping的结果

**Comment by 644163476** [comment]
import numpy as np
import random
from sko.GA import GA
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import basinhopping
from sko.PSO import PSO
from sko.DE import DE
from sko.GA import GA
from sko.SA import SA
import csv
import codecs

def fun(p):
    x1,=p
    a=np.zeros(3)
    a[0]=aw[1] + (aphy[2]+aphy[3]*np.log(x1) )*0.06678057 + 0.01962858*np.e**(ag[0]* (ag[2]-constant[8]))
    a[1]=aw[2] + (aphy[4]+aphy[5]*np.log(x1) )*0.06678057 +  0.01962858*np.e**(ag[0]* (ag[3]-constant[8]))
    a[2]=aw[3] + (aphy[6] + aphy[7] * np.log(x1)) * 0.06678057 + 0.01962858 * np.e ** (ag[0] * (ag[4] - constant[8]))
    b=np.zeros(3)
    b[0]=bw[1]+0.00275185*(constant[6]/ag[2])**1.9
    b[1]=bw[2]+0.00275185*(constant[6]/ag[3])**1.9
    b[2]=bw[3]+0.00275185*(constant[6]/ag[4])**1.9
    u=np.zeros(3)
    u[0] = b[0] / (b[0] + a[0])
    u[1] = b[1] / (b[1] + a[1])
    u[2] = b[2] / (b[2] + a[2])
    rs_deep=np.zeros(3)
    rs_deep[0] = (0.084 + 0.17 * u[0]) * u[0]
    rs_deep[1] = (0.084 + 0.17 * u[1]) * u[1]
    rs_deep[2] = (0.084 + 0.17 * u[2]) * u[2]
    Duc=np.zeros(3)
    Duc[0]=1.03*(1+2.4*u[0])**0.5
    Duc[1] = 1.03 * (1 + 2.4 * u[1]) ** 0.5
    Duc[2] = 1.03 * (1 + 2.4 * u[2]) ** 0.5
    Dub = np.zeros(3)
    Dub[0]=1.10*(1+5*u[0])**0.5
    Dub[1] = 1.10 * (1 + 5 * u[1]) ** 0.5
    Dub[2] = 1.10 * (1 + 5 * u[2]) ** 0.5
    k=np.zeros(3)
    k[0]=a[0]*b[0]
    k[1] = a[1] * b[1]
    k[2] = a[2] * b[2]



    v=(rs_blue-(rs_deep[0]*(1-np.e**((-1)*(1/np.cos(20.02)+Duc[0])*k[0]*x1))+B[0]*np.e**((-1)*(1/np.cos(20.02)+Dub[0])*k[0]*x1)))**2 + \
      (rs_green - (rs_deep[1] * (1 - np.e ** ((-1) * (1 / np.cos(20.02) + Duc[1]) * k[1] * x1)) + B[1] * np.e ** ((-1) * (1 / np.cos(20.02) + Dub[1]) * k[1] * x1))) ** 2 + \
      (rs_red - (rs_deep[2] * (1 - np.e ** ((-1) * (1 / np.cos(20.02) + Duc[2]) * k[2] * x1)) + B[2] * np.e ** ((-1) * (1 / np.cos(20.02) + Dub[2]) * k[2] * x1))) ** 2
    return v

def Rs():
    file = open("match1.csv", "r")
    lines = file.readlines()

    rows = len(lines)  # 文件行数

    datamat = np.zeros((rows, 6))  # 初始化矩阵

    row = 0
    for line in lines:
        line = line.strip(' ').split(',')

        dint = list(map(float, line))

        datamat[row, :] = dint[:]
        row += 1

    list1 = [1777, 9987, 3839, 4945, 644, 5421, 5737, 9703, 9361, 5861,8654, 9408, 1596, 9234, 755, 5224, 10000, 2822, 5796, 2577, 8050, 4699, 652, 4164, 3527, 4911, 9645, 9491, 2585, 9792, 6665, 7538, 4868, 10203, 2688, 9991, 9134, 6469, 4904, 9416, 9698, 3322, 8513, 9330, 3240, 2106, 7788, 3204, 6433, 225]

    blue = datamat[:, 3]
    green = datamat[:, 4]
    red = datamat[:, 5]
    for i in range(len(lines)):

        datamat[i, 3] = datamat[i, 3]/np.pi/ (1.5 * datamat[i, 3]/np.pi + 0.5*np.pi)

        datamat[i, 4] = datamat[i, 4]/np.pi / (1.5 * datamat[i, 4]/np.pi + 0.5*np.pi)

        datamat[i,5] = datamat[i, 5]/np.pi / (1.5 * datamat[i, 5]/np.pi + 0.5*np.pi)
    list2=np.zeros((50,6))
    for j in range(50):
        list2[j]=datamat[list1[j]]
    blue1 = list2[:, 3]
    green1 = list2[:, 4]
    red1 = list2[:, 5]
    print(datamat[list1[7],2])
    return blue1,green1,red1,datamat,list1

Rs_blue,Rs_green,Rs_red,datamat,list1= Rs()

aphy = [0.98902,0.018,0.751075,0.031963,0.35159,0.06712,0.70225,0.13615]
aphy = np.asarray(aphy)

aw = [0.00707,0.016008,0.06138,0.429]
aw = np.asarray(aw)
ag = [-0.014,443,492.1,559,665,440]
ag = np.asarray(ag)

bw = [0.0038*(400/443)**4.3,0.0038*(400/492.1)**4.3,0.0038*(400/559)**4.3,0.0038*(400/665)**4.3]
bw = np.asarray(bw)
angle = [20.02,9.9]
angle = np.asarray(angle)
bottam_reflance=[0.67669172,0.81203008,1.03759399,1.20300752]
bottam_reflance = np.asarray(bottam_reflance)
constant = [0.084,0.17,1.03,2.4,1.10,5.0,400,1,440]
constant = np.asarray(constant)
x0=[0.2,3]
x0=np.asarray(x0)
d = [0.002,1,0,30,2.5]
d = np.asarray(d)
B=np.zeros(3,dtype="float")
B[0]=0.040600/np.pi/(0.5*np.pi+1.5*0.040600/np.pi)
B[1]=0.052500/np.pi/(0.5*np.pi+1.5*0.052500/np.pi)
B[2]=0.019300/np.pi/(0.5*np.pi+1.5*0.019300/np.pi)

c=1.9


for m in range(50):
    rs_blue = Rs_blue[m]
    rs_green = Rs_green[m]
    rs_red = Rs_red[m]
    ga = GA(func=fun, n_dim=1, size_pop=30, max_iter=250, lb=[0.9], ub=[20], precision=1e-7)
    best_x, best_y = ga.run()
    print('best_x:', best_x, '\n', 'best_y:', best_y)
    print(datamat[list1[m], 2])
采用basinhooping
    result = basinhopping(fun, [5], niter=50, minimizer_kwargs={"method": "BFGS"})
    print(result.x)
这是basinhooping的结果

[4.62066055]
5.9
[7.39966695]
10.1
[4.19393513]
6.7
[4.34497455]
10.3
[3.18289491]
10.3
[5.00826925]
8.6
[4.73884525]
8.8
如果初始值设置接近真实值效果会更好 我查过basinhooping的官方文档 这个算法确实很依赖初始值

**Comment by 644163476** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guofei9987/scikit-opt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 上午9:12
收件人:&nbsp;"guofei9987/scikit-opt"<scikit-opt@noreply.github.com&gt;;
抄送:&nbsp;"644163476"<644163476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guofei9987/scikit-opt] 再用您的遗传算法求非线性目标函数的最小值时，设置完边界后，求得最优结果总是靠近边界，用python自带的全局最优basinhooping就不会产生该问题，不知是否是我在使用你的遗传算法时，参数设置有问题，能否提醒一下，该设置哪些参数 (#66)





 
完整贴一下，aphy，aw，Rs_blue
 
还有basinhooping的结果

**Comment by guofei9987** [comment]
所以遗传算法的结果是好于basinhooping的吗？
