### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by yan519354443** [guofei9987/scikit-opt#68]
1. 最近尝试用SA来做超参数搜索，但是对于神经网络的神经元个数，必须是整数，可能需要把x_new最后做下int转换
2. 学习率返回值有的时候过大

**Comment by guofei9987** [comment]
1. "x_new最后做下int转换" 这个按理应当在代码外面转换
2. 自定义一下合理的初始值。如果还不行可以改参数 [参见](https://scikit-opt.github.io/scikit-opt/#/zh/args?id=sa)，SA总共有3套，可以都试试。
