### ISSUE TITLE
Compare

### ISSUE THREAD

**Issue by guofei9987** [guofei9987/scikit-opt#7]

**Comment by gongyongqq** [comment]
> 针对GA_TSP，发现某些实现是这样的：对每个基因，随机找后面的基因，然后交换。这可能有问题，会使得靠后的基因，其实际变异概率更大。
> 附：
> 
> ```
>     size = len(individual)
>     for i in xrange(size):
>         if random.random() < indpb:
>             swap_indx = random.randint(0, size - 2)
>             if swap_indx >= i:
>                 swap_indx += 1
>             individual[i], individual[swap_indx] = \
>                 individual[swap_indx], individual[i]
> ```
> 
> 我这里的实现则是针对每个基因，随机选择一个（不限定先后，甚至可以是这个基因本身），然后进行交换。
> 我的实现：
> 
> ```
>     def mutation(self):
>         for i in range(self.size_pop):
>             for j in range(self.n_dim):
>                 if np.random.rand() < self.prob_mut:
>                     # n1, n2 = np.random.randint(0, self.len_chrom, 2)
>                     n = np.random.randint(0, self.len_chrom, 1)
>                     self.Chrom[i, j], self.Chrom[i, n] = self.Chrom[i, n], self.Chrom[i, j]
>         return self.Chrom
> ```
> 
> 究竟应当采用哪一个，目前存疑。

看论文学算法，而不要模仿网上随便找的不权威的代码。
