### ISSUE TITLE
doc of "More Simulated Annealing" missing

### ISSUE THREAD

**Issue by CarlDegio** [guofei9987/scikit-opt#70]
Click "More Simulated Annealing" but jump to "More Particle Swarm Optimization".
![image](https://user-images.githubusercontent.com/52379582/90729259-e2058200-e2f8-11ea-8cbe-d2668096f18e.png)

点击doc中的 “更多模拟退火算法” ，跳转到 “更多粒子群算法”。这部分内容暂时未上吗？

**Comment by guofei9987** [comment]
It is a bug. I set a wrong link: https://scikit-opt.github.io/scikit-opt/#/en/more_sa .  
The bug will be fixed tonight.

**Comment by guofei9987** [comment]
And thank you for this!

**Comment by CarlDegio** [comment]
再请教一个问题，如果我想用SA或者GA自己写规则解决TSP问题（举例），我应当模仿源码重写SA_TSP/GA_TSP中的方法，还是应当采用自定义算子（UDF）的方式？
如果更推荐后者，能否给出一个例子？

**Comment by guofei9987** [comment]
推荐用UDF,有两种方法（以GA_TSP为例）
1. 写UDF后用 `register` 注册一下
2. 或者新写一个类，继承 `GA_TSP`，覆写任意一个算子

**Comment by CarlDegio** [comment]
了解了，谢谢
