### ISSUE TITLE
GA（）当中参数的说明

### ISSUE THREAD

**Issue by 2learnsomething** [guofei9987/scikit-opt#73]
你好，我是刚刚开始接触优化算法的一些知识，对于括号当中的参数问题不是很理解，能麻烦再说明一下吗,谢谢.

**Comment by guofei9987** [comment]
参考文档 https://scikit-opt.github.io/scikit-opt/#/zh/args?id=%e5%85%a5%e5%8f%82%e4%b8%80%e8%a7%88

**Comment by 2learnsomething** [comment]
非常感谢您的解答
