### ISSUE TITLE
GA中dim不能为1？

### ISSUE THREAD

**Issue by zhangxiao123qqq** [guofei9987/scikit-opt#74]
您好，我对您给出的demo，做了一些改动，把自变量个数设为1。
```python
def schaffer(p):
    x = p
    # return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
    return x + 10 * np.sin(5 * x) + 7 * np.cos(4 * x)

 ga = GA(func=schaffer, n_dim=1, size_pop=50, max_iter=800, lb=[-1], ub=[1], precision=1e-7)
```
但是提示报错：

> Traceback (most recent call last):
  File "...", line 25, in <module>
    best_x, best_y = ga.run()
  File "...", line 80, in run
    self.crossover()
  File "...\venv\lib\site-packages\sko\operators\crossover.py", line 44, in crossover_2point_bit
    Chrom1 ^= mask2
ValueError: non-broadcastable output operand with shape (25,1,25) doesn't match the broadcast shape (25,25,25)

我理解的schaffer是用来定义自己的目标函数的这样对吗？ 那么为什么dim不能设为1呢？
另外您给的例子中
```python
    x1, x2 = p
    x = np.square(x1) + np.square(x2)
    return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
```
如果x1,x2为自变量的话，为什么要取一个x为中间量？ 仅仅是为了方便书写吗？
 感谢！

**Comment by zhangxiao123qqq** [comment]
另外，请问一下，constraint_eq  与constraint_ueq 是如何使用呢？ 谢谢您！

**Comment by guofei9987** [comment]
一元变量的问题参考 #65   
单个入参是为了和scipy的优化函数保持一致。另外还给 Advanced user 更多的灵活性。  
constraint_eq 与constraint_ueq 是等式约束和不等式约束，是函数组成的列表。具体用法看例子 https://scikit-opt.github.io/scikit-opt/#/zh/README?id=_1-%e5%b7%ae%e5%88%86%e8%bf%9b%e5%8c%96%e7%ae%97%e6%b3%95

**Comment by guofei9987** [comment]
## 一元变量的问题
一元变量也要按二元变量的格式来处理。
第二行 `x=p` 改为 `x, = p`

**Comment by zhangxiao123qqq** [comment]
> ## 一元变量的问题
> 一元变量也要按二元变量的格式来处理。
> 第二行 `x=p` 改为 `x, = p`

非常感谢！  已经尝试，效果很好！

**Comment by zhangxiao123qqq** [comment]
我理解的schaffer是用来定义自己的目标函数的这样对吗？ (即使我好奇为什么是schaffer而不是fun😄，schaffer有什么含义吗)
另外您给的例子中
```python
    x1, x2 = p
    x = np.square(x1) + np.square(x2)
    return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
```
如果x1,x2为自变量的话，为什么要取一个x为中间量？ 仅仅是为了方便书写吗？
感谢！

**Comment by guofei9987** [comment]
> 我理解的schaffer是用来定义自己的目标函数的这样对吗？ (即使我好奇为什么是schaffer而不是fun😄，schaffer有什么含义吗)
> 另外您给的例子中
> 
> ```python
>     x1, x2 = p
>     x = np.square(x1) + np.square(x2)
>     return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
> ```
> 
> 如果x1,x2为自变量的话，为什么要取一个x为中间量？ 仅仅是为了方便书写吗？
> 感谢！

https://en.wikipedia.org/wiki/Test_functions_for_optimization

**Comment by guofei9987** [comment]
- 单个入参是为了和scipy的优化函数保持一致。
- 另外单入参可以在函数中解析，给 Advanced user 更多的灵活性，例如动态维度、不确定的维度。

**Comment by zhangxiao123qqq** [comment]
> > 我理解的schaffer是用来定义自己的目标函数的这样对吗？ (即使我好奇为什么是schaffer而不是fun😄，schaffer有什么含义吗)
> > 另外您给的例子中
> > ```python
> >     x1, x2 = p
> >     x = np.square(x1) + np.square(x2)
> >     return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
> > ```
> > 
> > 
> > 如果x1,x2为自变量的话，为什么要取一个x为中间量？ 仅仅是为了方便书写吗？
> > 感谢！
> 
> https://en.wikipedia.org/wiki/Test_functions_for_optimization

原来是固定函数，还是该自己多查查的，我只做了翻译，发现为人名，十分感谢您！

**Comment by zhangxiao123qqq** [comment]
> > 我理解的schaffer是用来定义自己的目标函数的这样对吗？ (即使我好奇为什么是schaffer而不是fun😄，schaffer有什么含义吗)
> > 另外您给的例子中
> > ```python
> >     x1, x2 = p
> >     x = np.square(x1) + np.square(x2)
> >     return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
> > ```
> > 
> > 
> > 如果x1,x2为自变量的话，为什么要取一个x为中间量？ 仅仅是为了方便书写吗？
> > 感谢！
> 
> https://en.wikipedia.org/wiki/Test_functions_for_optimization



您好，我仔细对比schaffer函数，发现您demo中的好像是少了一个平方
```python
    # demo中的
    return 0.5 + (np.sin(x) - 0.5) / np.square(1 + 0.001 * x)
    # 改正后的
    return 0.5 + (np.square(np.sin(x)) - 0.5) / np.square(1 + 0.001 * x)
```

**Comment by guofei9987** [comment]
感谢！
你可以发个pr修改一下，有时间的还。

**Comment by zhangxiao123qqq** [comment]
> 感谢！
> 你可以发个pr修改一下，有时间的还。

已经发出，并且 help(GA)中 有几处  vaiiables 拼写错误，但是在源码中没找到。
```python
 |  lb : array_like
 |      The lower bound of every variables of func
 |  ub : array_like
 |      The upper bound of every vaiiables of func
 |  constraint_eq : list
 |      equal constraint
 |  constraint_ueq : list
 |      unequal constraint
 |  precision : array_like
 |      The precision of every vaiiables of func
```

**Comment by guofei9987** [comment]
https://github.com/guofei9987/scikit-opt/search?q=vaiiables&unscoped_q=vaiiables

**Comment by zhangxiao123qqq** [comment]
Very happy to learn about this project!
