### ISSUE TITLE
遗传算法是否支持不同长度的解

### ISSUE THREAD

**Issue by MaleicAcid** [guofei9987/scikit-opt#80]
假设问题是平面上许多个点，有的点会加分，有的点会扣分，且固定起点和终点， 希望用遗传算法规划出一条路径使得①分数尽可能高②距离尽可能短。途径的点数只需大于某个数即可(比如一共100个点, 至少走5个点)，不要求所有的点都走到 。多目标可以线性加权解决, 我纠结的是在不确定点数目的情况下, 应该如何对解进行编码呢, scikit-opt的遗传算法支持不同长度的解吗？

诚心求教大佬

**Comment by guofei9987** [comment]
感觉是可以的，每个个体对应两条基因，一条是TSP的，另一条是0-1的代表此处是否生效。
没写代码，感觉可以一试。
