### ISSUE TITLE
a little mistake of notes in GA.py

### ISSUE THREAD

**Issue by xu-kq** [guofei9987/scikit-opt#83]
scikit-opt/sko/GA.py /
**notes in line 26 and 27 seems to need exchanged.**

Of course, it doesn' matter for the whole project.
And, our class on intelligence algorithm introduce your work about genetic algorithm. Thanks for your devotion in open source community   :)
👍

**Comment by guofei9987** [comment]
Thank you for this!
A pr is welcome if you'd like to 😊

**Comment by xu-kq** [comment]
First time to pull request, intersting experience www
if my operation doesn't follow the git rule, I think you would clean up the mess 2333

**Comment by guofei9987** [comment]
> First time to pull request, intersting experience www
> if my operation doesn't follow the git rule, I think you would clean up the mess 2333

Very helpful and thank you! 
lol
