### ISSUE TITLE
请问如何优化神经网络代码呢？

### ISSUE THREAD

**Issue by Zhao-YB** [guofei9987/scikit-opt#92]
最近想用神经网络，却并不会如何用该模块对神经网络进行优化，请问有示范的例子吗？我用的是keras或者pytorch

**Comment by guofei9987** [comment]
这有个案例

能否使用神经网络来判断奇偶数？ - 幼鹰me的回答 - 知乎
https://www.zhihu.com/question/364113452/answer/961297759
