### ISSUE TITLE
Parallelizing the run of function passed into GA constructor

### ISSUE THREAD

**Issue by koralturkk** [guofei9987/scikit-opt#94]
Hi,

I would like to use GA for statsmodels sarimax function. I was wondering, how would it be possible to parallelize the fitting process of each individual in GA using torch. Crossovers, selections are parallelized however the function part is left out for such functionality. I would be glad if you can help me. 

`
    import torch
    import numpy as np
    import pandas as pd
    from scipy.stats import norm
    import statsmodels.api as sm
    import matplotlib.pyplot as plt
    from datetime import datetime
    import requests
    from io import BytesIO

    # Dataset
    wpi1 = requests.get('https://www.stata-press.com/data/r12/wpi1.dta').content
    data = pd.read_stata(BytesIO(wpi1))
    data.index = data.t
    # Set the frequency
    data.index.freq="QS-OCT"

    def arima(X):
          X = [int(x) for x in X]
          order = [X[0],X[1],X[2]]

          mod = sm.tsa.statespace.SARIMAX(data['wpi'], 
                                          order=order, 
                                          seasonal_order = [X[3],X[4],X[5],6],
                                          enforce_stationarity=False,
                                          enforce_invertibility=False
                                          )
          res = mod.fit(disp=False)
          #print(X)
          #print(res.aic)
          return res.aic

    ga = GA(func=arima, n_dim=6, size_pop=50, max_iter=50, lb=[0,0,0,0,0,0], ub=[6,4,6,4,3,4], precision=1)
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    
    ga.to(device=device)
    
    ga.run()
`

**Comment by guofei9987** [comment]
It is not recommended to use pytorch  to parallelize the fitting process.

I updated the current developer version to support it:
```
# %%Example of parallelize computing
import time


def schaffer1(p):
    x1, x2 = p
    time.sleep(1)  # pretend that the function is very complex and slow.
    return x1 ** 2 + x2 ** 2


def schaffer2(p):
    x1, x2 = p
    time.sleep(1)  # pretend that the function is very complex and slow.
    return x1 ** 2 + x2 ** 2


schaffer2.is_parallel = True
# %%
from sko.GA import GA

ga1 = GA(func=schaffer1, n_dim=2, size_pop=10, max_iter=3, lb=[-1, -1], ub=[1, 1], precision=1e-7)
ga2 = GA(func=schaffer2, n_dim=2, size_pop=10, max_iter=3, lb=[-1, -1], ub=[1, 1], precision=1e-7)

time_start = time.time()
best_x, best_y = ga1.run()
print('time cost:', time.time() - time_start, ' seconds')

time_start = time.time()
best_x, best_y = ga2.run()
print('time cost:', time.time() - time_start, ' seconds')
```

It will be released as the next version lately.

**Comment by koralturkk** [comment]
Is it because pytorch only supports data side parallelization not the process?

**Comment by guofei9987** [comment]
> Is it because pytorch only supports data side parallelization not the process?

The function may not for pytorch. https://github.com/guofei9987/scikit-opt/blob/5538c9774cc94e74e8f26c43a64fe9107aebc249/sko/GA.py#L219

**Comment by koralturkk** [comment]
Okay, how about replacing for loop with a parallel mapping within the GA?

**Comment by koralturkk** [comment]
https://pytorch.org/docs/stable/multiprocessing.html#spawning-subprocesses

**Comment by koralturkk** [comment]
Hey, I was also wondering, it might be a good idea to add a log dictionary storing X values and objective function results. If a same input due to GA process is given it will automatically output the result, which would boost the performance and help the package avoid repetitive calculations. Is it alright if I work on it and send a PR?

**Comment by guofei9987** [comment]
> Hey, I was also wondering, it might be a good idea to add a log dictionary storing X values and objective function results. If a same input due to GA process is given it will automatically output the result, which would boost the performance and help the package avoid repetitive calculations. Is it alright if I work on it and send a PR?

A PR is always welcome😄

And using `functools.lru_cache` might be a good idea

**Comment by koralturkk** [comment]
Thanks for the advice :)
