### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (16500,1) (544500,1) 

### ISSUE THREAD

**Issue by SPfree** [guofei9987/scikit-opt#97]
Firstly thanks for the authors and developers for this program! And I meet a mistake when I use the sky.PSO
following is my output of terminal

    best_x, best_y = de.run()
  File "/Users/boyaolong/opt/anaconda3/envs/ame=gurobienv/lib/python3.7/site-packages/sko/PSO.py", line 186, in run
    self.update_pbest()
  File "/Users/boyaolong/opt/anaconda3/envs/ame=gurobienv/lib/python3.7/site-packages/sko/PSO.py", line 147, in update_pbest
    self.need_update = self.pbest_y > self.Y
ValueError: operands could not be broadcast together with shapes (16500,1) (544500,1) 

the code when the mistake happen is 
de = PSO(func=object_func, n_dim=139, pop=16500, max_iter=80000, lb=lb_PSO, ub=ub_PSO,
       constraint_eq=constraint_eq, constraint_ueq=constraint_ueq)
Please help me!

**Comment by guofei9987** [comment]
> Firstly thanks for the authors and developers for this program! And I meet a mistake when I use the sky.PSO
> following is my output of terminal
> 
> ```
> best_x, best_y = de.run()
> ```
> 
> File "/Users/boyaolong/opt/anaconda3/envs/ame=gurobienv/lib/python3.7/site-packages/sko/PSO.py", line 186, in run
> self.update_pbest()
> File "/Users/boyaolong/opt/anaconda3/envs/ame=gurobienv/lib/python3.7/site-packages/sko/PSO.py", line 147, in update_pbest
> self.need_update = self.pbest_y > self.Y
> ValueError: operands could not be broadcast together with shapes (16500,1) (544500,1)
> 
> the code when the mistake happen is
> de = PSO(func=object_func, n_dim=139, pop=16500, max_iter=80000, lb=lb_PSO, ub=ub_PSO,
> constraint_eq=constraint_eq, constraint_ueq=constraint_ueq)
> Please help me!

Might be a problem of `object_func`. In that case see #65
