### ISSUE TITLE
PSO中，我优化的中间步骤很复杂，迭代代数多了就超出内存

### ISSUE THREAD

**Issue by ouxiaoxiao** [guofei9987/scikit-opt#99]
代码只保存每一次的最优值和参数，还是运行的所有数据

**Comment by guofei9987** [comment]
`pso.record_mode = False` 控制是否保存历史

**Comment by ouxiaoxiao** [comment]
> `pso.record_mode = False` 控制是否保存历史

这样就只有最优值和参数了吧，中间的运算过程每次会在内存清空吗

**Comment by guofei9987** [comment]
如果是 True，历史数据会存到 `pso.record_value`，否则不存

**Comment by ouxiaoxiao** [comment]
> 如果是 True，历史数据会存到 `pso.record_value`，否则不存

好滴 谢谢啦。 代码也比较好用，解答疑问还这么积极，太赞了
